### ISSUE TITLE
 Layout για την εμφάνιση των μελών σε ένα εργαστήριο και σε ένα ερευνητικό πρόγραμμα

### ISSUE THREAD

**Issue by ghost** [ioniodi/site-gr#10]
Οι εικόνες και τα ονόματα των μελών στο πλάι των εργαστηρίων είναι ικανοποιητικό?
π.χ.
![ScreenShot_20190314153034](https://user-images.githubusercontent.com/32746941/54360822-62d53e80-466e-11e9-927f-ab6d35105e68.png)

**Comment by ghost** [comment]
@epidrome

**Comment by epidrome** [comment]
το ερώτημα είναι πως θα συμπεριφέρεται σε διαφορετικές οθόνες και αν/πως μπορούμε να χρησιμοποιήσουμε στοιχεία-κώδικα που ήδη υπάρχουν
https://ioniodi.github.io/site-gr/people/

**Comment by ghost** [comment]
Αν κατάλαβα καλά, προτείνω να εμφανίζονται στο κάτω μέρος της κάθε παραγράφου και να μπουν διαχωριστικές γραμμές για να είναι σαφής ο διαχωρισμός μεταξύ εργαστηρίων και έτσι θα υποστηρίζει διάφορα μεγέθη οθόνης. Επίσης μπορεί να ελέγχει αν υπάρχει χώρος για να εμφανιστούν όλες οι εικόνες των μελών και να προσαρμόζεται περαιτέρω. Εξηγήστε μου λίγο πιο συγκεκριμένα, γιατί δεν κατάλαβα αν θέλετε αυτό που πρότεινα με μια προσαρμογή σε διάφορες οθόνες η κάτι άλλο. @epidrome

**Comment by epidrome** [comment]
όπως το λες είναι μια καλή ιδέα ή εναλλακτικά η λίστα με τα μέλη να εμφανίζεται μέσα στην σελίδα του εργαστηρίου, η οποία θα πρέπει να δημιουργηθεί αν δεν υπάρχει

**Comment by ghost** [comment]
Εγώ τείνω προς το πρώτο για να μειωθούν οι ανακατευθύνσεις σε νέες σελίδες. Αφού συμφωνείτε θα ξεκινήσω την υλοποίηση της δομής που πρότεινα.  @epidrome

**Comment by epidrome** [comment]
μια ιδέα για να αποφύγουμε τις πρόσθετες γραμμές είναι οι φωτογραφίες να εμφανίζονται ανάμεσα στον τίτλο και στην σύντομη περιγραφή του εργαστηρίου

γενικά είναι δύσκολο να πούμε ότι έχουμε τελικές προδιαγραφές, οπότε καλό είναι να έχουμε σταδιακή ενημέρωση με μικρές σταδιακές αλλαγές

**Comment by ghost** [comment]
Ωραία ξεκινάω με αυτό @epidrome
