### ISSUE TITLE
Δυναμικό περιεχόμενο στην αρχική σελίδα (Ερωτηση)

### ISSUE THREAD

**Issue by NikosAvg** [ioniodi/site-gr#102]
### Απορίες σχετικά με το θέμα.
Θα ήθελα να ρωτήσω τι εννοείτε δυναμικό περιεχόμενο πριν προχωρήσω σε δήλωση θέματος.
Στην αρχική σελίδα υπάρχουν τρία πεδία ένα για ανακοινώσεις ένα για ερευνητικά προγράμματα και ένα για τα εργαστήρια.
Σε αυτά αναφέρετε το δυναμικό περιεχόμενο ή θέλετε προσθήκη εξτρά πεδίου στο οποίο θα φαίνεται το δυναμικό περιεχόμενο.
@epidrome

**Comment by ghost** [comment]
@NikosAvg το #94 έχει ήδη πάρει το συγκεκριμένο θέμα.

**Comment by NikosAvg** [comment]
Δεν το είδα ευχαριστώ Kωστα κλείνω το issue

**Comment by epidrome** [comment]
επίσης το #83 είναι σχετικό, ίσως θα μπορούσαμε να έχουμε και ένα για φεισμπουκ, το οποίο είναι λίγο πιο δύσκολο γιατί το κόβουν κάποιοι

πάντως, υπάρχουν αρκετά διαθέσιμα (ορφανά) θέματα, ας μην τα συζητήσουμε εδώ, ανοίγεις νέο θέμα για όποιο σε ενδιαφέρει:

σελίδα 404 που να περιέχει αναζήτηση και σχετικά περιεχόμενα

Wiki: Τεκμηριωμένη ροή εργασίας για την ανάπτυξη και την παραγωγή, π.χ., πως είναι οργανωμένο το σύστημα και καλές πρακτικές ανάπτυξης

αυτοματισμένος αρχικός έλεγχος αιτημάτων, π.χ., είναι σωστό ένα μάθημα, καθηγητής, ανακοίνωση, κτλ

information architecture for images (reduce duplication) + git-lfs
