### ISSUE TITLE
Προσθηκη στη σελιδα 404 αναζήτηση και σχετικά περιεχόμενα.

### ISSUE THREAD

**Issue by NikosAvg** [ioniodi/site-gr#103]
### Δήλωση Θέματος
- Τίτλος: σελίδα 404 που να περιέχει αναζήτηση και σχετικά περιεχόμενα
- Θα προσπαθήσω να προσθέσω στην σελίδα 404 τη δυνατότητα αναζήτησης καθώς και εμφάνιση πιθανών θεμάτων που μπορεί να σχετίζονται με τη σελίδα που ο χρήστης προσπάθησε να μπει.
- Δυσκολία Θέματος: Δύσκολο

### Απορίες σχετικά με το θέμα
- Στο roadmap λέτε να περιέχει αναζήτηση τι ακριβώς εννοείτε να περιέχει πεδίο στο οποίο να μπορεί ο χρήστης να κάνει αναζήτηση στο site;

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [ ] Πριν προχωρήσω σε pull request έχω πάρει το "πράσινο φως"

**Comment by epidrome** [comment]
#43
