### ISSUE TITLE
Refactoring: _pages to the theme minimal-ionio

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#106]
### Δήλωση Θέματος
- Τίτλος επιλεγμένου θέματος
- Υπάρχουν αρκετά αρχεία τα οποία δεν είναι περιεχόμενο, αλλά κυρίως κώδικας (λικουιντ, παρουσίαση), π.χ., https://github.com/ioniodi/site-gr/tree/master/all_collections/_pages 
- Δυσκολία Θέματος: Εύκολο, Δύσκολο
- Σχετικά θέματα: #71 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος

**Comment by AsteriosP** [comment]
όπως ανέφερα και στο [τελευταίο μου review](https://github.com/ioniodi/site-gr/pull/105#pullrequestreview-398335295) πιστεύω ότι είναι μία σωστή πρακτική να μεταφέρουμε τον κώδικα liquid στο θέμα καί όχι εδώ

έχω ξεκινήσει να δουλεύω πάνω σε αυτό.

**Comment by dimpram** [comment]
> έχω ξεκινήσει να δουλεύω πάνω σε αυτό.

Αυτό το issue μπορεί να κλείσει με αφορμή τα 2 PR (ένα [εδώ](https://github.com/ioniodi/site-gr/pull/105) και ένα στο [minimal-ionio](https://github.com/ioniodi/minimal-ionio/pull/23)) του @provopoulos καθώς από ότι βλέπω μεταφέρει το μοναδικό include που υπάρχει εδώ, στο minimal-ionio.

**Comment by epidrome** [comment]
@jimDragon 
δες τα σχόλια μου στα 2 αιτήματα που λες

επιπλεον το θέμα αναφέρεται και στον φάκελο των σελίδων που έχει κώδικα και είναι εδώ

**Comment by dimpram** [comment]
@epidrome ναι τα είδα και γενικά συμφωνώ με τα σχόλια σας αλλά εμένα η γνώμη μου είναι πως η συγκεκριμένη περίπτωση μπορεί να αποτελέσει "εξαίρεση" καθώς το dynamic.html είναι ένα αρχείο το οποίο έχει άμεση σχέση με την δουλειά του @provopoulos και για τους λόγους που έχω και [εδώ](https://github.com/ioniodi/site-gr/pull/94#issuecomment-616082223) πιστεύω οτι διευκολύνει την κατάσταση.

> επιπλεον το θέμα αναφέρεται και στον φάκελο των σελίδων που έχει κώδικα και είναι εδώ

Εννοείτε το pages collection?

**Comment by provopoulos** [comment]
Το αρχικό PR του @Spirosvw ήταν καλά δομημένο υπό την έννοια πως η υλοποίηση δεν ήταν hardcoded, θα μπορούσε δηλαδή εξ' αρχής το `dynamic.html` να ενσωματωθεί στο αποθετήριο του θέματος.
Υπήρξε ένα μικρό πρόβλημα το οποίο χάλαγε την σωστή διάταξη του Twitter στο `index.html` με αποτέλεσμα να μην εμφανιζόταν σωστά στην στήλη το οποίο και διορθώθηκε.
Εφόσον λοιπόν έπρεπε να κάνω προσθήκη την υλοποίησή μου στο αποθετήριο θέματος αλλά και να κάνω μικρές αλλαγές στον κώδικα του Σπύρου στο `index.html`, το θεώρησα εύλογο να μεταφέρω το `dynamic.html` στο αποθετήριο θέματος.

**Comment by epidrome** [comment]
το θέμα κατοχυρώνεται στον @AsteriosP αν θες άνοιξε αντίστοιχο θέμα και εκεί αφού θα πρέπει να γίνουν δύο συντονισμένα αιτήματα

@provopoulos πράγματι είναι λίγο γκρι η κατάσταση και το πρόβλημα δεν είναι τόσο οι επιλογές που κάνουν οι συντελεστές αλλά η αρχιτεκτονική σε δύο αποθετήρια

@jimDragon θεωρείς πως υπάρχει κάποιο πρόβλημα με την αναβάθμιση του θέματος και αυτά τα αρχεία; νομίζω πως είναι ανεξάρτητα.

**Comment by provopoulos** [comment]
@epidrome 
Τόσο η υλοποίηση του Σπύρου, όσο και η δικιά μου δεν έχουν πρόβλημα αναβαθμισιμότητας καθώς είναι ξεχωριστά, ανεξάρτητα αρχεία.

**Comment by dimpram** [comment]
> @jimDragon θεωρείς πως υπάρχει κάποιο πρόβλημα με την αναβάθμιση του θέματος και αυτά τα αρχεία; νομίζω πως είναι ανεξάρτητα.

Δεν θα υπάρχει γιατί θα κρατήσουμε το index.html πάνω στο οποίο πατάνε και τα 2 αρχεία (dynamic.html, twitter-module.html).

**Comment by AsteriosP** [comment]
Δοκίμασα να περάσω το αρχείο `courses.md` από τον φάκελο `_pages:site-gr` στον φάκελο `_layouts:minimal-ionio` αλλά μετά την αλλαγή δεν έτρεχε σωστά η αντίστοιχη σελίδα. 
@jimDragon @provopoulos  μήπως έχετε να προτείνεται κάποιο workaround?

**Comment by dimpram** [comment]
Αυτό σου συνέβη μόνο στο courses.md? To courses.md δεν είναι layout, ανήκει στο collection _pages γιατί αποτελεί μια σελίδα που χρησιμοποιεί κάποιο layout. Αν θες να το κάνεις να είναι μέσα στον φάκελο layouts υποψιάζομαι θα πρέπει να αλλάξεις αρκετό κώδικα. 

Η δική μου πρόταση είναι να περάσεις όλο αυτό το collection στο θέμα(αν γίνεται).

Διαφορετικά θα πρέπει να μετατρέψεις το κάθε page σε layout. Αυτό μπορεί να γίνει κάπως έτσι:
1. Φτίαχνεις το αντίστοιχο layout στον φάκελο _layouts
2. Κάνεις copy paste τον κώδικα
3. Αλλάζεις το `layout:` στην σελίδα έτσι ώστε να χρησιμοποιεί τo κατάλληλο layout
*Επίσης δες και με το config αν χρειαστεί κάποια αλλαγη στα defaults*

Μπορεί να υπάρχει και άλλος τρόπος αλλά αυτοί είναι που σκέφτηκα τώρα.

**Comment by AsteriosP** [comment]
@jimDragon το έχω δοκιμάσει και με το posts.html, αλλά συμβαίνει το ίδιο πρόβλημα.

Αυτό που σου εμφανίζει στο αντίστοιχο link για τα posts είναι αυτό που φαίνεται παρακάτω
![image](https://user-images.githubusercontent.com/18286552/81168947-a68cb500-8fa0-11ea-9ba6-767961cdc477.png)

θα δοκιμάσω αυτά που μου πρότεινες

**Comment by epidrome** [comment]
ενημέρωσα το 1ο ποστ με το σχετικό θέμα #71 και πρόσθεσα την @korinaal 

όπως το καταλαβαίνω τώρα η λύση δεν είναι απλά μετακίνηση και θα πρέπει να δούμε χωριστά κάθε αρχείο, 

π.χ.:

1. τα courses, groups θα μπορούσαν να μείνουν εδώ, αλλά κάπου έξω από τις συλλογές, αφού δεν είναι συλλογές}

2. το people.md θα μπορούσε να γίνει layout στο θέμα

κτλ

**Comment by korinaal** [comment]
Bump!! Το κοιτάω εγώ!!
