### ISSUE TITLE
Bug: _posts shows random item, instead, show only recent

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#107]
### Δήλωση Θέματος
- Τίτλος επιλεγμένου θέματος
- Το αίτημα #94 δείχνει τυχαία τις ανακοινώσεις, θα πρέπει να δείχνει μόνο τις πρόσφατες, ίσως τυχαία, ίσως μόνο αν έχουν κάποια ετικέτα-κατηγορία, αρκεί να είναι πρόσφατες, π.χ., 30-90 μέρες
- Δυσκολία Θέματος: Εύκολο

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος

**Comment by Spirosvw** [comment]
Θα το κοιτάξω έγω αυτό μιας και ασχολήθηκα με την υλοποίηση του _posts

**Comment by Spirosvw** [comment]
Για το bug αυτό έχω να προτείνω δύο λύσεις:
1) Αυτή την στιγμή στο αρχείο index.html επιλέγεται ένας random αριθμός. Μπορώ να μειώσω το εύρος της random μεταβλητής έτσι ώστε να μπορεί να επιστρέψει αριθμούς στο εύρος πχ. [0,10] και έτσι να επίλεγεται μόνο ένα από τα δέκα τελευταία posts. Αυτό απαιτεί λίγες αλλαγές στον κώδικα και εκτελείται αρκετά γρήγορα.
Αρνητικά: Δεν βασίζεται στον χρόνο αλλά στην λίστα των posts
2) Μπορώ να προσθέσω στον κώδικα κάτι σαν αυτό:

{% assign timeframe = 604800 %}

  {% for post in site.posts %}
    {% assign post_in_seconds = post.last_modified_at | date: "%s" | plus: 0 %}
    {% assign recent_posts = "now" | date: "%s" | minus: timeframe  %}

    {% if post_in_seconds > recent_posts %}
      <a href="{{ post.url }}">{{ post.title }}</a>
    {% endif %}
  {% endfor %}

Αυτό το κομμάτι του κώδικα επιστρέφει τα posts του τελευταίου μήνα. Με αλλαγές μπορεί να χρησιμοποιηθεί ώστε να επιστρέφει ένα από αυτά δυναμικά.
Αρνητικά: Υπάρχει και η περίπτωση να επιστρέψει κενή λίστα εαν δεν έχουν γίνει δημοσιέυσεις στον μήνα αυτό.

**Comment by Spirosvw** [comment]
@jimDragon ή @andreanastil θα ήθελα να μου πείτε και εσείς την γνώμη σας και τις ιδέες σας.

**Comment by dimpram** [comment]
Για το πρώτο δεν είμαι σίγουρος αν καταλαβαίνω το αρνητικό. Ουσιαστικά λες οτι θα είναι όπως πριν απλά θα έχει λιγότερο εύρος, σωστά?

Το αρνητικό στο δεύτερο μπορεί να ξεπεραστεί και με ένα if υποθέτω αλλά νομίζω η πρώτη λύση είναι καλύτερη προγραμματιστικά. Θα μπορούμε να το παραμετροποιούμε αν αλλάξουμε γνώμη μελλοντικά.

**Comment by epidrome** [comment]
γιατί να μην δείχνουμε μόνο το πιο πρόσφατο;

όποιος θέλει να τα δει όλα ακολουθεί το λινκ "περισσότερα"

μάλιστα το αρχικό θέμα φαίνεται να έχει έτοιμες δυνατότητες οργάνωσης του ιστορικού:
https://mmistakes.github.io/minimal-mistakes/year-archive/

**Comment by Spirosvw** [comment]
Το πιο πρόσφατο μου φαίνεται και εμένα ως η πιο σωστή λύση. Η υλοποίηση είναι αρκετά απλή. Αν συμφωνεί και ο @jimDragon θα προχωρήσω στην υλοποίηση του για να κλείσει και το issue αυτό

**Comment by dimpram** [comment]
Ναι δεν υπάρχει προβλημα απο την μεριά μου. Δοκίμασε με το πιο πρόσφατο
