### ISSUE TITLE
Update footer links

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#108]
### Δήλωση Θέματος
- Τίτλος επιλεγμένου θέματος
- #67 υπάρχουν πολλές ιδέες στο αρχικό θέμα και στα σχετικά που θα μπορούσαν να συζητηθούν
- προσθήκη: επικοινωνία-γραμματεία, bbb.di.ionio.gr, διαγραφή: πρύτανης-κοσμήτορας (δεν είναι ρόλος του τμήματος) 
- Δυσκολία Θέματος: Πολύ εύκολο

### Υπενθυμίσεις
- [ ] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [ ] Πριν προχωρήσω σε pull request έχω πάρει το "πράσινο φως"

**Comment by Spirosvw** [comment]
Ίσως στο να γινόταν η προσθήκη των στοιχείων επικοινωνίας στο footer με ένα button που θα οδηγεί στην σελίδα που δημιούργησε ο @KonstantinosG  στο #98

**Comment by Spirosvw** [comment]
Όπως φαίνεται κάτω δεξιά στην εικόνα που έστειλα 

![git](https://user-images.githubusercontent.com/22668228/80686773-ed2a6d00-8ad1-11ea-9499-5ac1c2a6bc73.png)

**Comment by KonstantinosG** [comment]
@Spirosvw είναι καλή ιδέα και ταιριάζει να υπάρχει σε εκείνο το σημείο ο σύνδεσμος επικοινωνίας εαν συμφωνούν και οι υπόλοιποι θα προσωρήσω στην εισαγωγή της σελίδας στο footer.

**Comment by epidrome** [comment]
ενημέρωσα σχετικά το 1ο ποστ για την προσθήκη-διαγραφή λινκς

εκτός από την ενημέρωση σημαντική θα είναι και η συνοπτική τεκμηρίωση του σκεπτικού στο γουικι για τους μελλοντικούς συνεργάτες
