### ISSUE TITLE
Bug: tags link to external site (google scholar)

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#109]
### Δήλωση Θέματος
- Τίτλος επιλεγμένου θέματος
- use tags to show related content within the site
- Δυσκολία Θέματος: Εύκολο

nice catch by @korinaal #99 🚀

**Comment by andreanastil** [comment]
Το συγκεκριμένο το δουλεύω εγω ως μέρος του #111

**Comment by epidrome** [comment]
@andreanastil ΟΚ δικό σου, αλλά:

η καλή πρακτική είναι να το στέλνουμε ξεχωριστά τα επιμέρους αιτήματα ώστε να είναι όσο γίνεται πιο μικρά και στοχευμένα, έτσι ελαχιστοποιούμε την πιθανότητα για λάθη

εκτός και αν είναι κάτι που λύνεται αυτόματα με τις δυνατότητες του #111 

από μια διαγώνια ανάγνωση της τεκμηρίωσης, βλέπω ότι το ίδιο το τζέκιλ χωρίς πρόσθετα έχει κάποιες βασικές δυνατότητες δημιουργίας λίστας με ετικέτες:
https://jekyllrb.com/docs/posts/#categories-and-tags

οπότε μάλλον συμφέρει να λυθεί έτσι το πρόβλημα εδώ, και αν η συζήτηση στο #111 δώσει κάτι καλύτερο το αλλάζουμε τότε.

**Comment by epidrome** [comment]
επίσης, το κεντρικό θέμα φαίνεται να έχει σχετικό ντέμο με πολλές ετικέτες, το οποίο δίνει μια εύκολη λύση για εδώ καθώς και για #111 
https://mmistakes.github.io/minimal-mistakes/edge%20case/edge-case-many-tags/
