### ISSUE TITLE
Δημιουργία σελίδων για τις ανακοινώσεις από το 2017-2019

### ISSUE THREAD

**Issue by ylavdos** [ioniodi/site-gr#12]
Κάποια αρχεία τα οποία έχω βάλει να τα τραβάει από τα _docs αλλά και καποιες εικόνες δεν μου τις εμφανίζει στην ιστοσελίδα παρόλο που το github μου δείχνει οτι τις δέχεται κανονικά. Επίσης έχω ασχοληθεί και με τη "Δημιουργία (αυτόματης) λίστας μαθημάτων για την κάθε κατεύθυνση", "Ενημέρωση σελίδων για τα εργαστήρια και για τα ερευνητικά προγράμματα".

**Comment by ylavdos** [comment]
@epidrome

**Comment by epidrome** [comment]
παρατηρώ ότι έχεις κάνει 10άδες αλλαγές μαζεμένες, σε πολλά διαφορετικά αρχεία

καλύτερα να γίνουν τμηματικά, π.χ., ένα σετ με ανακοινώσεις, ένα σετ με εργαστήρια, ένα με ερευνητικά, κτλ

επίσης, για την ώρα, καλύτερα να μην έχουμε πρόσθετα αρχεία, όπως εικόνες και επισυναπτόμενα
