### ISSUE TITLE
Refactoring: git submodule for all_collections

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#120]
### Δήλωση Θέματος
- μεταφορά συλλογών σε εξωτερικό αρχείο και ενσωμάτωση του εδώ με git submodule
- Εκτιμώμενη δυσκολία: easy-hard?
- Σχετικοί συνεργατές: @p15zerv @constantinexisc @jimDragon @GIANNIS-AGGELIS 
- Σχετικά θέματα: #17 #18 #91 #106 #117 #125 

### Απορίες σχετικά με το θέμα (αν υπάρχουν)

Αυτές τις μέρες ξεκινάει το ανάλογο μάθημα στο 2ο μεταπτυχιακό του τμήματος, όπου ο στόχος είναι συμπληρωματικός: αυτόματη δημιουργία του οδηγού σπουδών του τμήματος (LaTeX-PDF).

Με δεδομένο ότι περισσότερα από τα μισά αρχεία είναι τα ίδια (π.χ., μαθήματα, εργαστήρια, προγράμματα), σκεφτόμουν την χρήση του git submodule, έτσι ώστε να απομονώσουμε σε διακριτά αποθετήρια (ένα ή περισσότερα?) τα αντίστοιχα αρχεία.

Νομίζω ότι είναι σχετικά εύκολο να γίνει, αλλά δεν έχω (ακόμη) εμπειρία σε git submodule 

θα ήθελα την γνώμη σας πρώτα, γιατί όπως το φαντάζομαι τελικά δεν θα μείνει σχεδόν κανένα αρχείο εδώ, οπότε ίσως να μπορέσουμε να το ενώσουμε πάλι με το θέμα;

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by ghost** [comment]
Κάποια σχόλια.

Αν ονομάσουμε τα αποθετήρια με το όνομα πχ "_allcollections" τότε τον φάκελο του sub module θα μπορεί να τον βλέπει το jekyll κανονικά στο build. Παρόμοια ονόματα θα μπούνε και σε ότι άλλο σπάσουμε από το κύριο αποθετήριο.

Το προβλημα είναι ότι τα sub modules δεν σχεδιάστηκαν για τον σκοπό που θέλουμε σε αυτό το issue. Συνήθως χρησιμοποιουνται όταν θέλουμε να μπορούμε να κανουμε pull και να κραταμε ενήμερο κάποιο αποθετήριο από το upstream αλλα δεν θέλουμε να χρησιμοποιήσουμε τις καινούργιες αλλαγές. Εμείς θέλουμε το εντελώς αντίθετο να είμαστε πάντα up to date με όλα τα submodules. 

Επίσης κάθε φορά που θα θέλουμε να περνάμε καινούργιο post η γενικά το οποιοδήποτε περιεχόμενο θα πρέπει να κάνουμε τα commit στο submodule και μετά στο κύριο αποθετήριο να κάνουμε πάλι commit ότι κάνουμε update το commit ref του submodule.

Μπορούμε να γράψουμε κάποιο bash script νομίζω για αυτό αλλά μόνο τοπικά θα δουλεύει δεν θα μπορέσουμε να το ενσωματώσουμε με κάποιο άλλο εργαλείο γιατί είναι πολύ edge case.

Για μένα δεν είναι δουλειά να το υλοποιήσω γρήγορα αλλα όπως είπα αρχιτεκτονικα είμαι αντίθετος, δεν θα μας βοηθήσει.

Για εναλλακτικές προσεγγίσεις σε αυτο που θέλετε να κάνετε σαν ιδέα θα το σκεφτώ για το μάθημα της Πέμπτης!

**Comment by p15zerv** [comment]
Δεν γνωρίζω (ακόμα) αρκετά για το git submodule για να σχολιάσω στο τεχνικό κομμάτι. Πάντως, μου φαίνεται λογικό από τη στιγμή που υπάρχουν κοινά αρχεία για διάφορες τέτοιες διαδικασίες του τμήματος, αυτά να είναι πάντα ενημερωμένα και κοινά σε όλες τις διαδικασίες. Αρχιτεκτονικά, όμως, δεν ξέρω αν αυτό θα έπρεπε να βασίζεται στο git, ούτως ή άλλως; Μου θυμίζει, ίσως, περισσότερο τη δουλειά μιας βάσης δεδομένων; Αν και θα μπορούσε να γίνει και μέσω του git φαντάζομαι...

Όπως και να έχει θα κοιτάξω κι εγώ λίγο για το submodule, να δω αν θα καταλήξω στο ίδιο με τον @constantinexisc, ώστε να συζητηθεί στο επόμενο μάθημα.

**Comment by epidrome** [comment]
> Μπορούμε να γράψουμε κάποιο bash script νομίζω για αυτό αλλά μόνο τοπικά θα δουλεύει δεν θα μπορέσουμε να το ενσωματώσουμε με κάποιο άλλο εργαλείο γιατί είναι πολύ edge case.

μάλλον θα απαιτεί μια (χειροκίνητη) ενέργεια εδώ ακόμη, αλλά δεν την λες και σκριπτ, ίσως να μπορεί να μπει μέσα στο χουκ του νετλιφαη

> You can make a submodule to follow the HEAD of a branch of a submodule remote repo

https://stackoverflow.com/questions/31769820/differences-between-git-submodule-and-subtree

**Comment by epidrome** [comment]
@constantinexisc ενημέρωσα το 1ο ποστ με λινκ στο σχετικό θέμα σου #18 γιατί το είχα ξεχάσει και δεν το σχολίασες

αν ο φάκελος τελικά βγει, θα πρέπει να κρατήσουμε και την ιστορία του

**Comment by dimpram** [comment]
Μήπως με το git submodule το project καταλήξει να είναι over-engineered? Υπάρχει πραγματικά η ανάγκη να απομονώσουμε τα collections σε ξεχωριστό/ά αποθετήριο/α?

**Comment by epidrome** [comment]
νομίζω πως ήδη είναι κάπως πολύπλοκο! ειδικά για τους νέους developer, 

αλλά είναι κάπως πιο απλό για αυτούς που βάζουν μόνο περιεχόμενο, οι οποίοι σε λίγο μπορεί να μην χρειάζονται καν πρόσβαση εδώ #125 

το μέλλον επίσης είναι κάπως ασαφές για το θέμα, αν τελικά αποκτήσει κληρονομικότητα
https://github.com/ioniodi/minimal-ionio/issues/2

αν όμως ισχύει η υπόθεση μου:

> τελικά δεν θα μείνει σχεδόν κανένα αρχείο εδώ, οπότε ίσως να μπορέσουμε να το ενώσουμε πάλι με το θέμα;

η τελική κατάσταση θα είναι πάλι δύο αποθετήρια, όπου το ένα μάλιστα (οι συλλογές) δεν θα έχει τίποτα που να θυμίζει jekyll.

η απάντηση στο ερώτημα σου εξαρτάται σε ποιον ρόλο-χρήση αναφέρεσαι

**Comment by dimpram** [comment]
> η τελική κατάσταση θα είναι πάλι δύο αποθετήρια, όπου το ένα μάλιστα (οι συλλογές) δεν θα έχει τίποτα που να θυμίζει jekyll.

Νομίζω οτι αυτό το έχουμε ήδη πετύχει σχεδόν.

Ειδικά αν ισχύει αυτό που είπε και ο @constantinexisc 

> κάθε φορά που θα θέλουμε να περνάμε καινούργιο post η γενικά το οποιοδήποτε περιεχόμενο θα πρέπει να κάνουμε τα commit στο submodule και μετά στο κύριο αποθετήριο να κάνουμε πάλι commit ότι κάνουμε update το commit ref του submodule.

δεν νομίζω να μας βοηθήσει πολύ. Μπορεί να κάνω και λάθος βέβαια γιατί δεν έχω εμπειρία με git submodules.

**Comment by epidrome** [comment]
> σχεδόν.

ο εχθρός του καλού, είναι το καλύτερο ;-)

δεν ξέρω αν ισχύει αυτό που είπε ο @constantinexisc δες αυτό:

> You can make a submodule to follow the HEAD of a branch of a submodule remote repo

https://stackoverflow.com/questions/31769820/differences-between-git-submodule-and-subtree

**Comment by epidrome** [comment]
πάντως περισσότερο με προβληματίζει ότι για πρώτη φορά έχουμε καλές οδηγίες και τεκμηριώση

οπότε δεν θα ήθελα να το πειράξουμε τόσο πολύ για την ώρα τουλάχιστον, ειδικά αν είναι να χαλάσουν οι οδηγίες

θα έλεγα ότι το θέμα εδώ έχει έναν ορίζοντα 1-2 χρόνια αν τελικά πάρει πράσινο φως
