### ISSUE TITLE
Layout for author sidebar in a course with two teachers

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#121]
### Δήλωση Θέματος
- κάποια μαθήματα έχουν δύο διδάσκοντες, στο ΜΠΣ ακόμη και τρεις, το πρόσφατο αίτημα από τον @p15zerv φαίνεται πως προσφέρει μια καλή βάση για μια λύση
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @p15zerv 
- Σχετικά θέματα: #119 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p15zerv** [comment]
Κάτι τέτοιο ίσως; 
https://adoring-yonath-300689.netlify.app/courses/semantic-and-social-web/

Είναι και backwards compatible σε περίπτωση που κάποιο μάθημα έχει μόνο έναν καθηγητή, π.χ.
https://adoring-yonath-300689.netlify.app/courses/language-technology/

**Comment by p15zerv** [comment]
Από όσα είπαμε στο σημερινό μάθημα μας κάνει κάτι τέτοιο, οπότε το αναλαμβάνω και θα κάνω σύντομα το αντίστοιχο PR.
