### ISSUE TITLE
html to markdown converters

### ISSUE THREAD

**Issue by Spirosvw** [ioniodi/site-gr#123]
### Δήλωση Θέματος
- Υπάρχουν έτοιμα εργαλεία που μετατρέπουν τα html αρχεία σε markdown
- Εκτιμώμενη δυσκολία:easy
- Σχετικοί συνεργατές: @NikosAvg 
- Σχετικά θέματα:

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
Δοκίμασα ένα (https://www.browserling.com/tools/html-to-markdown) και δουλεύει μέτρια

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by NikosAvg** [comment]
Το δοκίμασα και γω τώρα το συγκεκριμένο και όντως δεν μεταφέρει τελεία από το ενα στο άλλο,
γενικά νομίζω το πρόβλημα είναι ότι δεν υπάρχουν κάποια στοιχειά της html που να αντιστοιχούν σε κάτι στο md όπως τα  \<div>, \<span>
κτλ.
Επίσης για να γράψουμε σε md πρέπει το αρχείο να εχει κατάληξη .md, το οποίο άργησα να παρατηρήσω στο 404.html και εκανα κάποια άσκοπα commit, αλλιώς απλά τα δείχνει οπως τα γράφουμε.
Το οποίο δημιουργεί και ενα αλλο πρόβλημα, στον φάκελο _pages κάποια αρχεία είναι .md και κάποια .html χωρίς κάποιο συγκεκριμένο λόγο.
