### ISSUE TITLE
Δομή δεδομένων για τον χάρτη των κτιρίων

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#124]
### Δήλωση Θέματος
- Μεταφορά των συντεταγμένων στο front matter
- Εκτιμώμενη δυσκολία: hard
- Σχετικοί συνεργατές: @KonstantinosG @AsteriosP 
- Σχετικά θέματα: #69  #114

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@provopoulos καθώς έχουμε σε εκκρεμότητα σημαντικά αιτήματα προτείνω να προχωρήσουν η ενημέρωση του θέματος και η αλλαγή του ιστορικού πριν προχωρήσεις με αυτό το αίτημα

@jimDragon @constantinexisc 
μόλις κλείσουν τα τρέχοντα ανοιχτά αιτήματα προχωρήστε με τα δικά σας αιτήματα, 

ιδανικά μέσα στην τελευταία εβδομάδα των μαθήματων, δλδ μέχρι 5 Ιουνίου

αμέσως μετά θα έρθει ο @provopoulos να τεστάρει τα φρέσκα αποθετήρια με το αίτημα αυτού του θέματος

**Comment by provopoulos** [comment]
@epidrome 
Μπορώ να προχωρήσω στην υλοποίηση της δομή δεδομένων τώρα που έγινε η αναβάθμιση έκδοσης του MM στο αποθετήριο του θέματος; Κι αν ναι, στο καινούργιο αποθετήριο, https://github.com/ioniodi/sitegr, έτσι;
(( Να ανοίξω νέο ζήτημα στο νέο ή να προχωρήσω κατευθείαν σε PR μόλις είμαι έτοιμος;
Ευχαριστώ.

**Comment by epidrome** [comment]
@provopoulos 
θα δουλέψεις στο νέο-καθαρό:
https://github.com/ioniodi/sitegr
ανοίγεις εκεί νέο θέμα, γίνεται συζήτηση, και κάνεις εκεί αίτημα
προφανώς θα πρέπει να κάνεις νέο φορκ, γιατί η ιστορία ξαναγράφτηκε
έτσι θα έχεις την τιμή να κάνεις τα εγκαίνια 🍾 


εδώ μπορείς να δουλέψεις μόνο την τεκμηρίωση στο γουικι σύμφωνα με τις οδηγίες #112

**Comment by provopoulos** [comment]
@epidrome
Ευχαριστώ για τις διευκρινήσεις. Θα χρειαστούμε (λογικά) προσκλήσεις στο νέο αποθετήριο ώστε να έχουμε δικαιώματα εγγραφής και τροποποιήσεων.

**Comment by epidrome** [comment]
@provopoulos 

αν θες να:

1. ενημερώσεις το 1ο ποστ με ένα λινκ προς το αντίστοιχο θέμα στο νέο αποθετήριο;

2. να ενημερώσεις το γουικι με την βελτιωμένη τεκμηρίωση δομή;
https://github.com/ioniodi/site-gr/wiki/Contact-and-maps

**Comment by provopoulos** [comment]
@epidrome 
Good catches!
> 1. ενημερώσεις το 1ο ποστ με ένα λινκ προς το αντίστοιχο θέμα στο νέο αποθετήριο;

Done
> 2. να ενημερώσεις το γουικι με την βελτιωμένη τεκμηρίωση δομή;

Also done :: https://github.com/ioniodi/site-gr/wiki/Contact-Info
