### ISSUE TITLE
Διόρθωση της δομής των post και των project

### ISSUE THREAD

**Issue by GIANNIS-AGGELIS** [ioniodi/site-gr#126]
Από το pull request #125 φαίνεται ότι τα post και τα project δεν εμφανίζονται όλα. Αυτό οφείλεται στο γεγονός ότι η δομή του cms δεν συμφωνεί με την δομή που έχουνε τα post και τα project. Η δομή που καταλαβαίνει το cms είναι:

Post:
---
ref:
title:
excerpt:
tags:
categories:
---

Projects:
---
ref:
title:
excerpt:
partners:
web:
---

Στόχος είναι να  ελεγχθούν και να διορθωθούν όλα τα post και τα project

**Comment by epidrome** [comment]
@GIANNIS-AGGELIS 
μπορείς να προσθέσεις στο ποστ σου 1-2 ενδεικτικά λινκ με αρχεία που έχουν πρόβλημα;
ευχαριστούμε!

**Comment by GIANNIS-AGGELIS** [comment]
@epidrome 
Το λάθος στο φάκελο posts είναι ότι δεν ακολουθούν όλα την δομή έχοντας δυο φορές το πεδίο tag το οποίο πρέπει να αντικατασταθεί με το categories μερικά σχετικά link από posts:
[2017-03-16-dhlosi+paralavi-suggramatwn.md](https://github.com/ioniodi/site-gr/blob/master/all_collections/_posts/2017-03-16-dhlosi+paralavi-suggramatwn.md)
[2018-04-27-kan-didaktorikon.md](https://github.com/ioniodi/site-gr/blob/master/all_collections/_posts/2018-04-27-kan-didaktorikon.md)
[2018-05-30-katataktiries-18-19.md](https://github.com/ioniodi/site-gr/blob/master/all_collections/_posts/2018-05-30-katataktiries-18-19.md)

projects:
[ebusiness_forum.md](https://github.com/ioniodi/site-gr/blob/master/all_collections/_projects/ebusiness_forum.md)
[optical_fiber.md](https://github.com/ioniodi/site-gr/blob/master/all_collections/_projects/optical_fiber.md)

Η διόρθωση η οποία πρέπει να γίνει στα projects πρέπει στο πεδίο excerpt το περιεχόμενο του να βρίσκεται σε μια γραμμή..

**Comment by epidrome** [comment]
@GIANNIS-AGGELIS 
μπορείς να ενημερώσεις **το 1ο ποστ σου** 

ώστε να μην έχει το λινκ "εντιτ" και να είναι σαφές ποιο/α είναι τα λάθη, 

π.χ., σε κάποια βλέπω ότι έχει δύο φορές ταγκ

σκέψου ότι απευθύνεσαι σε εσένα πριν 4 χρόνια ;-)

**Comment by GIANNIS-AGGELIS** [comment]
@epidrome 
Στο πρώτο ποστ κατά λάθος πρόσθεσα τα Links εκεί και διόρθωσα το προηγούμενο ποστ. Στην ουσία το ένα λάθος είναι αυτό που αναφέρεις και άλλο είναι με τις γραμμές που αναφέρω στο προηγούμενο ποστ.

**Comment by p15zerv** [comment]
Νομίζω πως πλέον αρκετά αρχεία στα οποία εμφανιζόντουσαν 2 φορές τα tags έχουν διορθωθεί από το #128. Αν εμφανίζονται πλέον στο netlify, απομένουν μόνο οι αλλαγές στα projects.
