### ISSUE TITLE
Περιορισμός του μεγέθους του preview κειμένου στις ανακοινώσεις/projects της αρχικής σελίδας

### ISSUE THREAD

**Issue by ghost** [ioniodi/site-gr#129]
### Δήλωση Θέματος
- Περιορισμός του μεγέθους του preview κειμένου στις ανακοινώσεις/projects της αρχικής σελίδας
- Εκτιμώμενη δυσκολία: easy
- Σχετικοί συνεργατές: @Spirosvw 
- Σχετικά θέματα: #107 

### Παρατηρήσεις σχετικά με το θέμα
Έχει παρατηρηθεί ότι αν μια ανακοίνωση η project έχει αρχική παράγραφο που είναι πολύ μεγάλη τότε η αρχική σελίδα θα καταλήξει να φαίνεται παραμορφωμένη. Προτείνεται ο περιορισμός του αριθμού χαρακτήρων έτσι ώστε να παραμένει το layout της σελίδας σταθερό. Μπορεί να προστεθουν αποσιωπητικά μετά από πχ. 100 χαρακτήρες.

![image](https://user-images.githubusercontent.com/11950996/81844318-8ee09e00-9557-11ea-8c98-fb86d787e8e7.png)

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by Spirosvw** [comment]
Solved it! 

![img2](https://user-images.githubusercontent.com/22668228/81919772-ee36c080-95e0-11ea-8f26-7f739f92a0d7.png)

Ειναι εντάξει?
Ο έλεγχος γίνεται και για τα posts και για τα projects
