### ISSUE TITLE
Wiki: Collections και κεντρικός φάκελος

### ISSUE THREAD

**Issue by p15zerv** [ioniodi/site-gr#133]
### Δήλωση Θέματος
- Προσθήκη τεκμηρίωσης σχετικά με τον κεντρικό φάκελο των collections, καθώς και πιθανώς του περιεχομένου των collections, γενικότερα.
- Σχετικά θέματα: #112 #58

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
- Με αφορμή την τεκμηρίωση του κεντρικού φακέλου για τις συλλογές, σκέφτομαι πως μάλλον θα ήταν συνετό να γίνει και μια γενικότερη περιγραφή για τις συλλογές και το περιεχόμενο τους (π.χ. αποφυγή html/πολύ κώδικα jekyll). Όμως, φαίνεται ήδη να [υπάρχει ήδη σελίδα για τα posts](https://github.com/ioniodi/site-gr/wiki/Categories,-tags-for-_posts), που θα μπορούσαν πιθανώς να ενσωματωθούν σε μία κεντρική με τα υπόλοιπα collections (ένας φάκελος, μία σελίδα!)
- Αν θεωρούμε πως η γενικότερη περιγραφή των collections θα ήταν προτιμότερη, αυτό θα ήταν καλύτερο να γίνει συνεργατικά, για εξοικονόμηση χρόνου και για καλύτερη τεκμηρίωση από όποιον είναι περισσότερο εξοικειωμένος με κάθε collection.

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p15zerv** [comment]
Αφήνω εδώ μια πρώτη εκδοχή για τον κεντρικό φάκελο και μπορεί να γίνει συζήτηση για γενικότερη τεκμηρίωση:

> 
> Η [έκδοση Jekyll 3.7](https://jekyllrb.com/news/2018/01/02/jekyll-3-7-0-released/) επιτρέπει τη δημιουργία ενός κεντρικού φακέλου για την αποθήκευση όλων των collections ενός project. Το κύριο όφελος αυτής της αλλαγής είναι η απλούστευση της δομής του κεντρικού φακέλου. Για να επιτευχθεί η συγκέντρωση των συλλογών σε ένα φάκελο, πέρα από τη μετακίνηση των σχετικών αρχείων, μια [πολύ απλή τροποποίηση του config ήταν αναγκαία](https://github.com/ioniodi/site-gr/pull/62/files#diff-aeb42283af8ef8e9da40ededd3ae2ab2). 
> 
> Μερικές παρατηρήσεις για αυτή την αλλαγή
> - Απαιτείται έκδοση Jekyll 3.7+
> - Αν χρειαστεί να αναιρεθεί, όσοι δουλεύουν σε κάποιο αρχείο σχετικό με τα collections, θα πρέπει πρώτα να κάνουν update τα branch τους, προτού επιχειρήσουν κάποιο PR
> 
> 
> Σχετικό issue: [#58](https://github.com/ioniodi/site-gr/issues/58)

**Comment by dimpram** [comment]
Νομίζω οτι είναι κάπως περιττό να γράψουμε τεκμηρίωση για κάθε collection. Το collection από μόνο του σαν concept είναι αρκετά σαφές και το να μπούμε στην διαδικασία να περιγράψουμε το περιενχόμενο τους θα ήταν κάπως ανούσιο. Θα μπορούσαμε όμως να είχαμε ένα page στο οποίο να περιγράφουμε γενικά την δομή του project δηλαδή:
- για ποιο λόγο είνα χωρισμένο σε 2 αποθετήρια
- ποιες πρακτικές ακολοθούμε για τα includes
- την πρακτική του φακέλου all_collections όπως είπες


και ενδεχομένως και άλλα αν μπορείς να σκεφτείς.

**Comment by epidrome** [comment]
@p15zerv 
> Με αφορμή την τεκμηρίωση του κεντρικού φακέλου για τις συλλογές, σκέφτομαι πως μάλλον θα ήταν συνετό να γίνει και μια γενικότερη περιγραφή για τις συλλογές και το περιεχόμενο τους (π.χ. αποφυγή html/πολύ κώδικα jekyll). Όμως, φαίνεται ήδη να υπάρχει ήδη σελίδα για τα posts, που θα μπορούσαν πιθανώς να ενσωματωθούν σε μία κεντρική με τα υπόλοιπα collections (ένας φάκελος, μία σελίδα!)

η αρχική σελίδα στο γουικι ενημερώθηκε και έχει μια ενότητα για τα αρχεία, η σελίδα που λες θα μπορούσε να προστεθεί εκεί με τίτλο π.χ., style-guide ή κάτι τέτοιο

@jimDragon 
> για ποιο λόγο είνα χωρισμένο σε 2 αποθετήρια ποιες πρακτικές ακολοθούμε για τα includes

θα μπορούσες να προσθέσεις μια σύντομη σελίδα στην 1 ενότητα της αρχικής με τίτλο: Αρχιτεκτονική, ίσως θα μπορούσες να κάνεις και κάποιο κατ-πειστ από την άλλη σελίδα που δουλεύεις για την ροή εργασίας;

**Comment by dimpram** [comment]
Ναι θα το δω

**Comment by p15zerv** [comment]
Λέω να προσθέσω κι εγώ το κομμάτι μου στο #154, τότε. Θεωρώ ταιριάζει ενδιάμεσα από τις 2 παραγράφους της @korinaal. Παραθέτω τη μορφή του κειμένου αν συνενωθούν:

> Εφόσον στο αποθετήριο του `site-gr`, η βασική ιδέα είναι να μην υπάρχει πολύς κώδικας...
> 
>Η [έκδοση Jekyll 3.7](https://jekyllrb.com/news/2018/01/02/jekyll-3-7-0-released/) επιτρέπει τη δημιουργία ενός κεντρικού φακέλου για την αποθήκευση όλων των collections ενός project. Το κύριο όφελος αυτής της αλλαγής είναι η απλούστευση της δομής του κεντρικού φακέλου. Για να επιτευχθεί η συγκέντρωση των συλλογών σε ένα φάκελο, πέρα από τη μετακίνηση των σχετικών αρχείων, μια [πολύ απλή τροποποίηση του config ήταν αναγκαία](https://github.com/ioniodi/site-gr/pull/62/files#diff-aeb42283af8ef8e9da40ededd3ae2ab2). Αξίζει να αναφερθεί πως αν χρειαστεί να αναιρεθεί η δομή του κεντρικού φακέλου, όσοι δουλεύουν σε κάποιο αρχείο σχετικό με τα collections, θα πρέπει πρώτα να κάνουν update τα branch τους, προτού επιχειρήσουν κάποιο PR
>
> Αναφορικά με τα `all_collections`, δεν υπάρχει λόγος ...
> 
> Σχετικά issues: #106, #58

**Comment by korinaal** [comment]
@p15zerv πολύ καλό, νομίζω πως δένει πλήρως με αυτά που έχω προσθέσει και εγώ. Εύγε!

**Comment by epidrome** [comment]
υποθέτω ότι έχει περαστεί
οπότε το κλείνω ώστε να γίνει η μεταφορά του γουηκι τις επόμενες μέρες
