### ISSUE TITLE
Wiki: Layout for author sidebar in a course with multiple teachers

### ISSUE THREAD

**Issue by p15zerv** [ioniodi/site-gr#134]
### Δήλωση Θέματος
- Προσθήκη τεκμηρίωσης για την προσθήκη του sidebar με τις πληροφορίες καθηγητών για μαθήματα με πολλαπλούς διδάσκοντες.
- Σχετικά θέματα: #121, #131, #132, #133

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by p15zerv** [comment]
Πιθανώς θα μπορούσε να προστεθεί σε μία κεντρική σελίδα #133, αλλά μια πρώτη εκδοχή:

> Ένα μάθημα, το οποίο αναπαρίσταται από ένα αρχείο στο collection `courses`, μπορεί να διδάσκεται από έναν ή περισσότερους καθηγητές. Κατά την εμφάνιση του μαθήματος στο site, το θέμα διαχειρίζεται σωστά την εμφάνιση κάθε περίπτωσης, εμφανίζοντας τις πληροφορίες κάθε καθηγητή με βάση το κλειδί του στο πεδίο `author`, που αντιστοιχίζεται σε ένα κλειδί στο αρχείο `data/authors.yml`. 
> 
> Για την τροποποίηση ενός μαθήματος, είναι αναγκαίο να τροποποιηθεί το αντίστοιχο αρχείο στα `courses`. 
> Σε περίπτωση που υπάρχει μονάχα ένας καθηγητής, το πεδίο `author` αρκεί να είναι της μορφής `author: <key>`. Εφόσον υπάρχουν περισσότεροι, το πεδίο θα πρέπει να είναι της μορφής:
> ```
> author:
>   - <key1>
>   - <key2>
>   ...
> ```
> 
> Σημαντικό είναι να αναφερθεί πως στη σελίδα ενός καθηγητή αναγράφονται όλα τα μαθήματα τα οποία διδάσκει. Σε αυτά θα πρέπει να συμπεριλαμβάνονται αυτόματα και μαθήματα, τα οποία δεν διδάσκονται μονάχα από έναν καθηγητή. Αυτή τη στιγμή, αυτό δεν ισχύει και είναι ανοιχτό θέμα [#132](https://github.com/ioniodi/site-gr/issues/132).
> 
> Ως προς τη συντήρηση του αποθετηρίου, για την προσθήκη του συγκεκριμένου feature, χρειάστηκε η [τροποποίηση δύο αρχείων του θέματος](https://github.com/ioniodi/minimal-ionio/pull/27/files), τα οποία προέρχονται από το minimal-mistakes. Επομένως, θα πρέπει να υπάρξει προσοχή κατά τη μελλοντική αναβάθμιση του θέματος, ώστε να μην αντικατασταθούν τα συγκεκριμένα αρχεία.
> 
> Σχετικά issues: [#121](https://github.com/ioniodi/site-gr/issues/121), [#131](https://github.com/ioniodi/site-gr/issues/131), [#132](https://github.com/ioniodi/site-gr/issues/132)

**Comment by p15zerv** [comment]
Έβαλα assign όσους ήταν reviewers. Sorry για την έξτρα δουλειά, ένα τελευταίο τσεκ για τις αλλαγές μου!

**Comment by epidrome** [comment]
άριστη τεκμηρίωση και συνοδευτικό άνοιγμα νέων θεμάτων για τους επόμενους, μπράβο!!

**Comment by p15zerv** [comment]
Κλείνω κι εδώ το issue, αν έχει άλλος σχόλιο μπορεί να ξανα-ανοίξει
