### ISSUE TITLE
Wiki: Δυναμικό Περιεχόμενο στην αρχική σελίδα

### ISSUE THREAD

**Issue by Spirosvw** [ioniodi/site-gr#140]
### Δήλωση Θέματος
- Προσθήκη τεκμηρίωσης σχετικά με την λειτουργία του δυναμικού περιεχομένου στην αρχική σελίδα (Posts & Projects) καθώς και πιθανές αλλαγές που θα μπορουσαν να υλοποιηθούν.
- Σχετικά θέματα: #78 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by Spirosvw** [comment]
Περιεχόμενο του Wiki: https://github.com/Spirosvw/site-gr/wiki/%CE%94%CF%85%CE%BD%CE%B1%CE%BC%CE%B9%CE%BA%CF%8C-%CE%A0%CE%B5%CF%81%CE%B9%CE%B5%CF%87%CF%8C%CE%BC%CE%B5%CE%BD%CE%BF-%CE%91%CF%81%CF%87%CE%B9%CE%BA%CE%AE%CF%82-%CE%A3%CE%B5%CE%BB%CE%AF%CE%B4%CE%B1%CF%82?fbclid=IwAR0r-wHO5kSVSpgrTFR1bEsWBNkvRAfb2BeMmwEsWl9Lfe4ZBhuvNGH-reQ

**Comment by KonstantinosG** [comment]
Είναι πολύ καλή και ολοκληρωμένη η δουλειά! Μπράβο @Spirosvw. Πιστεύω είναι έτοιμο για εισαγωγή.

**Comment by korinaal** [comment]
Πραγματικά πολύ λεπτομερής περιγραφή! Ένα πολύ πολύ μικρό σχόλιο, έχεις βάλει ένα παραπάνω τόνο στη λέξη "εύχρηστο", στην αρχή της εισαγωγικής σου παραγράφου. Εξαιρετική δουλειά! @Spirosvw

**Comment by andreanastil** [comment]
Πολύ καλή και λεπτομερής περιγραφή, πιστεύω θα βοηθήσει σε όποιον ίσως χρειαστεί οποιαδήποτε λεπτομέρεια πάνω στο κομμάτι. Μπράβο @Spirosvw !

**Comment by provopoulos** [comment]
Αρκετά συνοπτικό και κατατοπιστικό παρά την εκτεταμένη υλοποίησή του. Καλή δουλειά, μπράβο!!
