### ISSUE TITLE
Σελίδα Επικοινωνίας με γεωγραφικούς χάρτες. Αλλαγές - Προσθήκες

### ISSUE THREAD

**Issue by KonstantinosG** [ioniodi/site-gr#142]
### Αλλαγές και προσθήκες στην σελίδα "Επικοινωνία"
- Μετακίνηση της σελίδας επικοινωνίας στο κάτω μέρος της ιστοσελίδας (sitemap). Μία ιδέα είναι ο σύδεσμος να εισαχθεί κάτω από την κατηγορία "Χρήσιμοι Σύνδεσμοι". Η αρχική σκέψη ήταν να μπει κάτω από την κατηγορία "Προσωπικό" όμως δεν μου ταίριαζε καθώς εκεί είναι οι σελίδες των καθηγητών και όχι σχετικές πληροφορίες με το τμήμα.
- Εισαγωγή συνδέσμου πλοήγησης στους χάρτες σε κάθε marker που υποδεικνύουν σημεία ενδιαφέροντος του Ιονίου Πανεπιστημίου εντός της πόλης.
- Σχετικοί συνεργατές: @Spirosvw @AsteriosP @p15zerv 
- Σχετικά θέματα: #69 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [ ] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by KonstantinosG** [comment]
Σε πρώτη φάση έχει μετακινηθεί ο σύνδεσμος της σελίδας επικοινωνίας στο κάτω μέρος όπου βρίσκεται το sitemap.
Αναφορικά με τους χάρτες προσπάθησα να εισάγω υπερσύνδεσμο στα markers που δείχνουν την τοποθεσία όμως για κάποιον λόγο δεν μπορεί να δεχθεί την τοποθεσία κανονικά, με αποτέλεσμα να έχει τοποθετήσει τον marker στην Ερυθρά θάλασσα... Φαίνεται και στην εικόνα:

![Screenshot 2020-05-29 at 10 20 05](https://user-images.githubusercontent.com/12886878/83247761-b321b900-a1ac-11ea-88cc-39ca0b53358c.png)

Ο σύνδεσμος που περιέχει τους χάρτες στη μορφή που περιέγραψα είναι [εδώ](https://confident-brattain-27ead2.netlify.app/contact/)


Σκεφτόμουν να βάλω κάτω από τον χάρτη ένα κομμάτι που να περιέχει την περιήγηση στις τοποθεσίες που περιλαμβάνονται εντός του. Με στυλ:
## Περιήγηση με τους προσωπικούς χάρτες σε:
#### Ιόνιο Πανεπιστήμιο, Τμήμα Πληροφορικής, Κτίριο Γαληνός
#### Ιόνιο Πανεπιστήμιο, Τμήμα Πληροφορικής, Κτίριο Γραμματειών
#### Ιόνιο Πανεπιστήμιο, Τμήμα Πληροφορικής, Κτίριο Αρεταίος
#### Φοιτητική Λέσχη
#### Ιόνιος Ακαδημία - NOC
#### Ιόνιο Πανεπιστήμιο, Ανάκτορα, Γραφεία Καθηγητών
#### Ιόνιο Πανεπιστήμιο, Τμήμα Ιστορίας, Αμφιθέατρα Διδασκαλίας

Οπότε τα markers να μην περιέχουν τον υπερσύνδεσμο και το κείμενο παραπάνω να είναι clickable.

**Comment by AsteriosP** [comment]
καλή ιδέα, εφόσον δεν μπορούν να μπουν στους χάρτες.

το μόνο που δεν μου άρεσε είναι οι τίτλοι των συνδέσμων ίσος είναι πολύ "Ιόνιο Πανεπιστήμιο, Τμήμα Πληροφορικής"

**Comment by KonstantinosG** [comment]
Ωραία. Συμφωνώ με την αλλαγή στα ονόματα. Την έχω ήδη κάνει. Δείτε [εδώ](https://confident-brattain-27ead2.netlify.app/contact/) τις αλλαγές.

**Comment by KonstantinosG** [comment]
Έκανα τις τελευταίες αλλαγές. [Σύνδεσμος](https://confident-brattain-27ead2.netlify.app/contact/).
Έχει γίνει δοκιμή στον υπολογιστή μου (mac λειτουργικό) και σε iOS συσκευή. Οι χάρτες και στις δύο περιπτώσεις ανόιγουν και εμφανίζουν την κατάλληλη πινέζα από την τοποθεσία που επέλεξε ο χρήστης.

**Comment by epidrome** [comment]
> Εισαγωγή συνδέσμου πλοήγησης στους χάρτες σε κάθε marker που υποδεικνύουν σημεία ενδιαφέροντος του Ιονίου Πανεπιστημίου εντός της πόλης.

μήπως αυτό θα έπρεπε να είναι ξεχωριστό θέμα?

**Comment by KonstantinosG** [comment]
> μήπως αυτό θα έπρεπε να είναι ξεχωριστό θέμα?

Στο μάθημα είχαμε πει πως αυτές οι αλλαγές που ανέφερα παραπάνω μένουν να υλοποιηθούν. Επειδή όμως η μετακίνηση του συνδέσμου από το πάνω μέρος της οθόνης στο κάτω ήταν μικρή σε υλοποίηση, την πρόσθεσα και αυτήν εδώ απλά. Επίσης, λόγω ότι ο χρόνος είναι περιορισμένος επειδή τελειώνουμε και για να μην καθυστερήσω τους @constantinexisc και @jimDragon τα έκανα σε ένα issue για να γίνει γρηγορότερα η διαδικασία των review και merge.

**Comment by provopoulos** [comment]
@KonstantinosG 
Θα επιχειρήσω να υλοποιήσω την δομή δεδομένων για τους χάρτες όπως αναφέρεται στο ζήτημα https://github.com/ioniodi/site-gr/issues/124.
Θεωρείς πως θα υπάρχει (ή και όχι) κάποια πιθανή σύγκρουση συγκριτικά με τις προσθήκες που επιχειρείς να κάνεις σε αυτό το ζήτημα;
Η ιδέα είναι πως θα δημιουργηθεί μια δομή https://github.com/ioniodi/site-gr/tree/master/_data για τις τοποθεσίες των κτηρίων σε αυτό το αποθετήριο με τα δεδομένα και θα τα τραβάει για να τα αναπαραστήσει το αποθετήριο του θέματος.
Ευχαριστώ!

**Comment by KonstantinosG** [comment]
@provopoulos 
Θεωρώ πως δεν θα υπάρξει πρόβλημα με τις αλλαγές που θέλεις να κάνεις όμως σε κάθε περίπτωση θα πρέπει προηγουμένως να γίνουν merge τα PR και στο [minimal-ionio #32](https://github.com/ioniodi/minimal-ionio/pull/32) (εκεί βρίσκονται οι αλλαγές για τη σελίδα "Επικοινωνία" στο αρχείο communication-info.html) αλλά και εδώ στο site-gr #144.
