### ISSUE TITLE
Wiki: Γεωγραφικοί χάρτες.

### ISSUE THREAD

**Issue by KonstantinosG** [ioniodi/site-gr#146]
### Δήλωση Θέματος
- Περιγραφή και ανάλυση των εργαλείων που χρησιμοποιήθηκαν για την εισαγωγή των γεωγραφικών χαρτών στη σελίδα "Επικοινωνία".
- Σχετικά θέματα: #69, #142

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by KonstantinosG** [comment]
Η σελίδα του wiki βρίσκεται [εδώ](https://github.com/KonstantinosG/site-gr/wiki/City-maps---Embed). Αναμένω σχόλια για να προχωρήσω στην εισαγωγή της στο ioniodi/site-gr

**Comment by Spirosvw** [comment]
Πολύ καλή τεκμηρίωση της δουλειάς σου και με αρκετό χρήσιμο υλικό για μελλοντικούς χρήστες. Μπράβο @KonstantinosG!

**Comment by AsteriosP** [comment]
Πολύ καλό wiki Μπράβο

**Comment by korinaal** [comment]
Το γεγονός ότι έχεις συμπεριλάβει τα εμπόδια δίνει ένα εκπαιδευτικό ύφος και μου αρέσει πολύ. Ωστόσο, εν τέλει θεωρώ πως δεν γίνεται κατανοητό από την περιγραφή, το αν λειτουργεί ή όχι ο κώδικας που παραθέτεις. Αν γίνει πιο ξεκάθαρο αυτό το κομμάτι, τότε η περιγραφή θα ναι άριστη! Σε κάθε περίπτωση, συγχαρητήρια! @KonstantinosG

**Comment by KonstantinosG** [comment]
> Το γεγονός ότι έχεις συμπεριλάβει τα εμπόδια δίνει ένα εκπαιδευτικό ύφος και μου αρέσει πολύ. Ωστόσο, εν τέλει θεωρώ πως δεν γίνεται κατανοητό από την περιγραφή, το αν λειτουργεί ή όχι ο κώδικας που παραθέτεις. Αν γίνει πιο ξεκάθαρο αυτό το κομμάτι, τότε η περιγραφή θα ναι άριστη! Σε κάθε περίπτωση, συγχαρητήρια! @KonstantinosG

Έγιναν οι αλλαγές. Είναι κάτω ακριβώς από τον κώδικα όπου αναφέρθηκες @korinaal. [Link](https://github.com/KonstantinosG/site-gr/wiki/City-maps---Embed)

**Comment by andreanastil** [comment]
Πολύ αναλυτική η περιγραφή με βοηθητικά παράδειγμα εισαγωγής χάρτη και markers. Επίσης, βοηθητική η περιγραφή των εμποδίων για μελλοντική ενσωμάτωση ή και επέκταση της δουλειάς σου. Μπράβο @KonstantinosG !

**Comment by provopoulos** [comment]
@KonstantinosG 
Για λόγους συνοχής, θα ήθελες να συγχωνεύσουμε τα 2 Wiki μας ώστε να μην υπάρχουν επαναλήψεις στην τεκμηρίωση της ιστοσελίδας;

Μπορείς να ελέγξεις το δικό μου ζήτημα εδώ: https://github.com/provopoulos/test/wiki/Contact_DS

Έχω μια ιδέα για το πως μπορεί να είναι το τελικό αποτέλεσμα αλλά θα ήθελα να ξέρω αν σε βρίσκει σύμφωνο αυτή η κίνηση.

**Comment by provopoulos** [comment]
@KonstantinosG
Οι αλλαγές για την ενοποίηση της συγκεκριμένης τεκμηρίωσης βρίσκονται εδώ: https://github.com/provopoulos/test/wiki/v2
Αναμένω κάποιο σχόλιο καθώς θα προχωρήσω στην ενσωμάτωση σύντομα ώστε να ολοκληρωθεί και τυπικά το δικό μου κομμάτι της τεκμηρίωσης.

**Comment by provopoulos** [comment]
Consolidated at: https://github.com/ioniodi/site-gr/wiki/Contact-Info
