### ISSUE TITLE
Wiki: Courses

### ISSUE THREAD

**Issue by korinaal** [ioniodi/site-gr#147]
### Δήλωση Θέματος
- Τεκμηρίωση των αλλαγών που σχετίζονται με την οργάνωση των μαθημάτων σε επιλογής, υποχρεωτικά και κατεύθυνσης.
- Σχετικά θέματα: #71 #79 #112 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by korinaal** [comment]
Στόχος είναι η σωστή κατηγοριοποίηση του συνόλου των μαθημάτων που παρέχονται από το Πρόγραμμα Σπουδών του Πανεπιστημίου. Οι βασικές κατηγορίες είναι: 
1. Μαθήματα Κορμού (Υποχρεωτικά) 
2. Μαθήματα Κατεύθυνσης Πληροφοριακών Συστημάτων 
3. Μαθήματα Κατεύθυνσης Ανθρωπιστικών Επιστημών και 
4. Μαθήματα Επιλογής

Μέσω αυτής της οργάνωσης είναι εύκολο για τον εκάστοτε χρήστη να εντοπίσει και να μεταβεί στην κατηγορία και στο εξάμηνο που τον ενδιαφέρει, εξαιτίας του πίνακα που παρέχεται. Επιπλέον, με δεδομένο ότι το κάθε μάθημα εισάγεται αυτόματα από τον φάκελο `all_collections` και με βάση το `type` του, εάν κάποιος επιθυμεί να εισάγει/τροποποιήσει κάποιο μάθημα, αρκεί να προσέξει να βάλει το σωστό `type`. Είναι απαραίτητο να σημειωθεί, πως τα διαθέσιμα `types` είναι: 
1. `M` για τα Μαθήματα Κορμού (Υποχρεωτικά)
2. `I` για τα Μαθήματα Κατεύθυνσης Πληροφοριακών Συστημάτων
3. `H` για τα Μαθήματα Κατεύθυνσης Ανθρωπιστικών Επιστημών
4. `O` για τα Μαθήματα Επιλογής

**ΠΡΟΣΟΧΗ:** Όλα τα types είναι με αγγλικούς χαρακτήρες!!!

Επίσης, σημειώνεται πως για την ορθή εμφάνιση του τύπου, η αντιστοίχιση μεταξύ αυτού και του πλήρους ονόματός του, πραγματοποιείται στο αρχείο `table.html` στο `minimal-ionio`. Π.χ. για να μην φαίνεται ένα σκέτο `M` στη σελίδα ενός μαθήματος, μέσω της αντιστοίχισης αυτής θα εμφανίζεται ολόκληρη η ονομασία `Υποχρεωτικό`.

Τέλος, θα ήταν δυνατό να προσαρμοστεί εύκολα η προαναφερόμενη λογική για οποιοδήποτε Πρόγραμμα Σπουδών, φτιάχνοντας αντίστοιχα `types` για κάθε κατηγορία μαθήματος.

**ΣΗΜΕΙΩΣΗ** Υπάρχει ήδη το κείμενο στο Wiki. Θα ήθελα μια γνώμη για πιθανή βελτίωσή του.

**Comment by p15zerv** [comment]
Πολύ καλή τεκμηρίωση, ειδικά το warning για τους αγγλικούς χαρακτήρες πιθανό να φανεί χρήσιμο σε κάποιον ατυχή. Από εμένα είναι οκ!
