### ISSUE TITLE
Wiki: Update Contributors Guide

### ISSUE THREAD

**Issue by korinaal** [ioniodi/site-gr#148]
### Δήλωση Θέματος
- Σύντομη τεκμηρίωση για τη χρήση του template για τη δημιουργία νέου issue. Προσθήκη μιας παραγράφου στο ήδη υπάρχον "Contributors Guide".
- Σχετικά θέματα: #57 #112 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by korinaal** [comment]
Ανοίγοντας ένα νέο θέμα, δίνεται η δυνατότητα να ακολουθήσουμε ένα συγκεκριμένο template, βάσει του οποίου εκτός από τον τίτλο, ορίζουμε επιγραμματικά τις επικείμενες αλλαγές που σκεφτόμαστε/σκοπεύουμε να κάνουμε (σκεπτόμενοι το κατά πόσο και πώς αυτές επηρεάζουν συνολικά το project και όχι μόνο το κομμάτι της υλοποίησης), την εκτιμώμενη δυσκολία αυτού, καθώς και σχετικά θέματα ή/και συνεργάτες. Επιπλέον, μπορούμε να θέσουμε κάποιες απορίες (εφόσον υπάρχουν). Με τον τρόπο αυτό, γίνεται πλήρως κατανοητό το τί θέλουμε να πετύχουμε, ενισχύοντας τη συνεργατικότητα και συνεργασία.

**ΣΗΜΕΙΩΣΗ** Υπάρχει ήδη η παράγραφος στο Wiki. Θα ήθελα μια γνώμη για πιθανή βελτίωσή της.

**Comment by p15zerv** [comment]
Μια χαρά κι εδώ! Βλέπω, μιας και υπάρχει ήδη στο wiki, ότι κολλάει η ροή στο σημείο που έχει προστεθεί, οπότε από εμένα μπορεί να περαστεί και officially!

**Comment by Spirosvw** [comment]
Πολύ καλό και straightforward! Μπραβο @korinaal! Η μόνη προσθήκη/σχόλιο που έχω να κάνω, είναι η εισαγωγή των links των σχετικών Issues και του κώδικα για πιθανές αλλαγές από μελλοντικούς χρήστες. Nevertheless good job!

**Comment by dimpram** [comment]
Πολύ χρήσιμη προσθήκη στο guide! Εγώ δεν έχω κάποιο σχόλιο.
