### ISSUE TITLE
Wiki: Bίντεο στο υπόβαθρο της αρχικής σελίδας

### ISSUE THREAD

**Issue by Spirosvw** [ioniodi/site-gr#150]
### Δήλωση Θέματος
-Προσθήκη τεκμηρίωσης σχετικά με την λειτουργία του βίντεο στο υπόβαθρο της αρχικής σελίδας καθώς και πιθανές αλλαγές που θα μπορουσαν να υλοποιηθούν.
- Σχετικά θέματα: #95 , #139 , #138 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by Spirosvw** [comment]
https://github.com/Spirosvw/site-gr/wiki/%CE%92%CE%AF%CE%BD%CF%84%CE%B5%CE%BF-%CF%83%CF%84%CE%BF-%CF%85%CF%80%CF%8C%CE%B2%CE%B1%CE%B8%CF%81%CE%BF-%CF%84%CE%B7%CF%82-%CE%91%CF%81%CF%87%CE%B9%CE%BA%CE%AE%CF%82-%CE%A3%CE%B5%CE%BB%CE%AF%CE%B4%CE%B1%CF%82

**Comment by AsteriosP** [comment]
από εμένα είναι green light, πολύ καλό wiki

**Comment by p15zerv** [comment]
Πολύ αναλυτική η τεκμηρίωση, good job! 

Ένα θέμα που θυμάμαι είχε αναφερθεί σε κάποιο μάθημα είναι πως τα βίντεο πρέπει να έχουν συγκεκριμένη ανάλυση; Υπάρχει αναφορά σε κάτι σχετικό στην τεκμηρίωση, οπότε ίσως το καλύπτει, απλώς το υπενθυμίζω μήπως έχει ξεχαστεί κάποιο κομματάκι.

Κατά τα άλλα, κάποια μικρά φραστικά:
- Η πρώτη πρόταση θέλει κάποια αλλαγή, λείπει νομίζω ένα ρήμα.
- Να προστεθεί το άρθρο στην πρόταση "Ο πηγαίος κώδικας της υλοποίησης αυτής βρίσκεται __στα__ αρχεία:"

**Comment by andreanastil** [comment]
Πέρα από τα σχόλια του @p15zerv, που έχουν περαστεί, το wiki είναι πολύ καλό και πλήρες με πρόταση και πηγές για μελλοντική τροποποίση.

**Comment by epidrome** [comment]
@Spirosvw 
για κάποιον λόγο φαίνομαι σας συγγραφέας!? ίσως επειδή άλλαξα τον τίτλο ή/και μετέφερα το περιεχόμενο, δεν θυμάμαι, συγνώμη!
https://github.com/ioniodi/site-gr/wiki/Video-background-on-home-page

επίσης δεν φαίνεται μια εικόνα
