### ISSUE TITLE
Wiki: Συντομεύσεις πλοήγησης στο footer της σελίδας

### ISSUE THREAD

**Issue by AsteriosP** [ioniodi/site-gr#153]
### Δήλωση Θέματος
- Προσθήκη τεκμηρίωσης σχετικά με τις συντομεύσεις πλοήγησης στο footer της σελίδας
- Εκτιμώμενη δυσκολία: easy
- Σχετικά θέματα: #67 #108 

[**DEMO**](https://github.com/AsteriosP/site-gr/wiki/%CE%A3%CF%85%CE%BD%CF%84%CE%BF%CE%BC%CE%B5%CF%8D%CF%83%CE%B5%CE%B9%CF%82-%CF%80%CE%BB%CE%BF%CE%AE%CE%B3%CE%B7%CF%83%CE%B7%CF%82-%CF%83%CF%84%CE%BF-footer-%CF%84%CE%B7%CF%82-%CF%83%CE%B5%CE%BB%CE%AF%CE%B4%CE%B1%CF%82)

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by Spirosvw** [comment]
@AsteriosP το Wiki περιγράφει αρκετά καλά την υλοποίησή των footer links. Αν θες πρόσθεσε και το #108  ως σχετικό link που δεν έχει υλοποιηθεί ακόμα.

**Comment by korinaal** [comment]
Πολύ κατατοπιστικό @AsteriosP στο σύνολό του, ιδιαίτερα η περιγραφή του παραδείγματος με τον κώδικα. Ωστόσο, προσωπικά δεν μου είναι ξεκάθαρη η σύνδεση που υπάρχει με το #108, με τον τρόπο που το περιγράφεις και επίσης, θα ήθελα να εξηγήσεις περαιτέρω τον τρόπο επιλογής των links.

**Comment by andreanastil** [comment]
Η περιγραφή του shortcuts.yml είναι κατανοητή. Θα συμφωνήσω και εγώ με τους @Spirosvw  και @korinaal, ίσως αξίζει να προστεθεί πώς ακριβώς κατέληξες στην επιλογή της υλοποίησης των συντομέυσεων πλοήγης και δύο λόγια παρπάνω για το λινκ του κάθε issue. Κατά τ' άλλα μπραβο!

**Comment by AsteriosP** [comment]
@Spirosvw @korinaal @andreanastil @KonstantinosG πέρασα τις αλλαγές που προτείνατε

δείτε το [DEMO](https://github.com/AsteriosP/site-gr/wiki/%CE%A3%CF%85%CE%BD%CF%84%CE%BF%CE%BC%CE%B5%CF%8D%CF%83%CE%B5%CE%B9%CF%82-%CF%80%CE%BB%CE%BF%CE%AE%CE%B3%CE%B7%CF%83%CE%B7%CF%82-%CF%83%CF%84%CE%BF-footer-%CF%84%CE%B7%CF%82-%CF%83%CE%B5%CE%BB%CE%AF%CE%B4%CE%B1%CF%82)

**Comment by epidrome** [comment]
@AsteriosP 
αν θες να το περάσεις στο γουήκι εδώ γιατί θα γίνει μεταφορά του στο νέο αποθετήριο και σε λίγο θα κλειδώσει εδώ
