### ISSUE TITLE
Wiki: Αρχιτεκτονική και Refactoring _pages

### ISSUE THREAD

**Issue by korinaal** [ioniodi/site-gr#154]
### Δήλωση Θέματος
- Με αφορμή τη συζήτηση στο #133 και την πρόταση για προσθήκη μιας σελίδας στο wiki με τίτλο "Style-Guide", συμφωνώ αυτή να εισαχθεί. Ως προς το περιεχόμενό της, μπορεί να συμπεριληφθεί, όπως αναφέρεται: ο διαχωρισμός των δύο αποθετηρίων, οι πρακτικές για τα includes, καθώς και το refactoring των `_pages` που αποτελεί την τεκμηρίωση του PR μου #135.
- Σχετικοί συνεργατές: @p15zerv @jimDragon @epidrome 
- Σχετικά θέματα: #133, #106 

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by korinaal** [comment]
Η τεκμηρίωση για το refactoring `_pages`, είτε προστεθεί είτε όχι στη σελίδα "Style-Guide", προτείνω να είναι η παρακάτω:

Εφόσον στο αποθετήριο του `site-gr`, η βασική ιδέα είναι να μην υπάρχει πολύς κώδικας, καλό είναι να υπάρχουν 'include', ώστε να μην είναι τόσο εμφανής ο κώδικας που χρησιμοποιείται για την εκάστοτε λειτουργία. Για παράδειγμα, στα `_pages` που απαιτείται πολύς κώδικας, αυτός έχει μεταφερθεί στο `minimal-ionio` και καλείται πλέον με τη χρήση των 'include'. Αξίζει να σημειωθεί ότι η συγκεκριμένη πρακτική, καλό θα είναι να εφαρμόζεται σε κάθε νέα προσθήκη στο αποθετήριο.

Αναφορικά με τα `all_collections`, δεν υπάρχει λόγος να εμπεριέχουν τα `_pages` μιας και αποτελούν μια πιο γενική έννοια, για αυτό και έχουν μεταφερθεί εκτός των `all_collections`. Κατόπιν της μεταφοράς τους, τίθεται το ζήτημα ότι το όνομα και το url κάποιων `_pages` συμπίπτει με το φάκελο στα `all_collections`. Έτσι, για να δοθεί προτεραιότητα στα `_pages` και να αντιμετωπιστεί το πρόβλημα έχουν προστεθεί τα permalinks.

Σχετικό issue: #106

**Comment by p15zerv** [comment]
Προσωπικά θα συμφωνήσω ότι ταιριάζει να μπει σε κάποιο style guide η τεκμηρίωσή σου, ειδικά εφόσον παρέχει και οδηγίες/καλές πρακτικές.

**Comment by andreanastil** [comment]
Αφού κατάλαβα τι εννοούσες με το refactoring, συμφωνώ με την υλοποίηση για τη μεταφορά όλου το κώδικα στο minimal-ionio, έτσι ώστε το site-gr να χρησιμοποιείται μόνο για την επεξεργασία του περιεχομένου. 
Όσο για το style guide, εφόσον έχει γίνει η μεταφορά καλό είναι να υπάρχει για να ανατρέχουν για σχετικές οδηγίες και πρακτικές.

**Comment by dimpram** [comment]
> Η βασική ιδέα είναι να μην υπάρχει πολύς κώδικας, καλό είναι να υπάρχουν 'include', ώστε να μην είναι τόσο εμφανής ο κώδικας που χρησιμοποιείται για την εκάστοτε λειτουργία.

Φαντάζομαιι εδώ εννοείς τον φάκελο `includes` στο minimal-ionio. Καλό θα ήταν να το διευκρινήσεις αυτό γιατί ενδεχομένως μετά να φτιάξουν τον φάκελο και στο site-gr

**Comment by epidrome** [comment]
ίσως ο όρος `αρχιτεκτονική` (=υπάρχει μια μορφή που φαίνεται, αλλά υπάρχει και μια δομή που δεν φαίνεται τόσο καθαρά αλλά καθορίζει-επηρεάζει την μορφή) 

να είναι τελικά περισσότερο κατάλληλος για το νόημα της συζήτησης εδώ, οπότε το πρόσθεσα ως ενότητα στον πίνακα περιεχομένων του γουικι.

επειδή γράφουμε πρώτη φορά τεκμηρίωση πρέπει να παρατηρούμε τι γραφουν οι άλλοι και να προσέχουμε για επικαλύψεις ή/και αμφισημίες-ασάφειες
