### ISSUE TITLE
Wiki: Tagcloud 

### ISSUE THREAD

**Issue by andreanastil** [ioniodi/site-gr#157]
### Δήλωση Θέματος
- Προσθηκή τεκμηρίωσης για το tagcloud της ιστοσελίδας των ανακοινώσεων.
- Σχετικοί συνεργατές: @GIANNIS-AGGELIS @jimDragon 
- Σχετικά θέματα: #111 #99 #59 

[Demo Wiki Page](https://github.com/andreanastil/site-gr/wiki/Tagcloud)

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
ενημέρωσα το 1ο ποστ με σχετικά θέματα-συνεργάτες

σε ένα από τα δύο γουίκι θα μπορούσε να προστεθεί και ένα λινκ προς το #125 αφού εκεί θα γράφονται οι ανακοινώσεις και θα μπαίνουν οι ετικέτες

**Comment by andreanastil** [comment]
> ενημέρωσα το 1ο ποστ με σχετικά θέματα-συνεργάτες
> 
> σε ένα από τα δύο γουίκι θα μπορούσε να προστεθεί και ένα λινκ προς το #125 αφού εκεί θα γράφονται οι ανακοινώσεις και θα μπαίνουν οι ετικέτες

@epidrome Ευχαριστώ για το update! Έγινε ένα μικρό rephrase στην τελευταιά παράγραφο και προστέθηκε το wiki CMS Netlify, καθώς και το [issue #4](https://github.com/ioniodi/sitegr/issues/4) του sitegr που προτείνει ο @GIANNIS-AGGELIS.

**Comment by GIANNIS-AGGELIS** [comment]
@andreanastil Εμενα μου φαίνεται κατανοητό το wiki το οποίο έχεις φτιάξει.  Επίσης εξηγείς με ωραίο τρόπο το pr που άνοιξα.

**Comment by p15zerv** [comment]
Πολύ καλό! Θα έλεγα καλύπτει τις διαφορετικές κατηγορίες χρηστών που προβλέπει το wiki. Ίσως θα μπορούσε να μπει στο τέλος μία λίστα με σχετικά issues όπως συνηθίζεται στις περισσότερες σελίδες, τα οποία υπάρχουν ήδη στο παρόν issue.

**Comment by andreanastil** [comment]
> Πολύ καλό! Θα έλεγα καλύπτει τις διαφορετικές κατηγορίες χρηστών που προβλέπει το wiki. Ίσως θα μπορούσε να μπει στο τέλος μία λίστα με σχετικά issues όπως συνηθίζεται στις περισσότερες σελίδες, τα οποία υπάρχουν ήδη στο παρόν issue.

Thank you, done!

**Comment by andreanastil** [comment]
Εφόσον έχω λάβει 3 feedback, προχωράω στην ενσωμάτωση του Wiki.
