### ISSUE TITLE
Wiki Docs: Data Structure for Contact section

### ISSUE THREAD

**Issue by provopoulos** [ioniodi/site-gr#158]
### Δήλωση Θέματος
- Προσθήκη τεκμηρίωσης σχετικά με την δημιουργία δομής δεδομένων για την δυναμική αναπαράσταση περιεχομένου στην ενότητα ['Επικοινωνία'](https://epic-hamilton-da9ac8.netlify.app/contact/) της ιστοσελίδας.
- Εκτιμώμενη δυσκολία: Δύσκολο
- Σχετικά θέματα: #69, #142, #124

**DEMO: https://github.com/provopoulos/test/wiki/Contact_DS**

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request θα πάρω ετικέτα green light

**Comment by epidrome** [comment]
@provopoulos 
πέρασε μια εβδομάδα και δεν έχουμε σχόλια από τους συντελεστές

αν θες να το περάσεις στο γουήκι εδώ γιατί θα γίνει μεταφορά του στο νέο αποθετήριο και σε λίγο θα κλειδώσει εδώ
