### ISSUE TITLE
Επεξεργασια και Ελεγχος Δεδομενων Μαθηματων

### ISSUE THREAD

**Issue by 0xDockerman** [ioniodi/site-gr#21]
Θα επεξεργαστω το πρωτα 20 μαθηματα (με αλφαβητικη σειρα)

- Ενημέρωση της βιβλιογραφίας κάθε μαθήματος με σύνδεσμο προς τα βιβλία του εύδοξου
- Αλλαγη link παλιων eclass με open-courses
- Διορθωση ωραριων και φροντηριων μαθηματων

**Comment by epidrome** [comment]
20 είναι πολλά, αρκεί να κάνεις 2-3, ότι θες, ευχαριστώ!
