### ISSUE TITLE
Ενημέρωση και προσθήκη νέων στοιχείων για τα μαθήματα του τελευταίου εξαμήνου

### ISSUE THREAD

**Issue by p15zerv** [ioniodi/site-gr#25]
Θα ανανεώσω όλες τις πληροφορίες σχετικά με τα μαθήματα του τελευταίου εξαμήνου:
* Προσθήκη Ή εξαμήνου στο courses.md (αυτή τη στιγμή λείπει)
* Ενημερωση περιγραφής, διδασκόντων, ωραρίων, βιβλιογραφίας
* Αλλαγή link από e-class σε open-courses
* Προσθήκη ενός νέου καθηγητή στους people και authors

**Comment by epidrome** [comment]
ο τίτλος δεν είναι σε συμφωνία με το σχόλιο, οπότε ενδέχεται κάποιοι να κάνουν κάτι παράλληλα

επίσης το συνολικό πακέτο περιλαμβάνει πολλά αρχεία τα οποία μάλλον θα οδηγήσουν σε σύγκρουση και σε ακύρωση του αιτήματος

**Comment by p15zerv** [comment]
Τροποποιήθηκε ο τίτλος και το σχόλιο
