### ISSUE TITLE
Ενημέρωση και προσθήκη των μαθημάτων από το 7 εξάμηνο

### ISSUE THREAD

**Issue by GIANNIS-AGGELIS** [ioniodi/site-gr#31]

**Comment by GIANNIS-AGGELIS** [comment]
Η δουλιά η συγκεκριμένη έχει γίνει σε αυτό το [pull request](https://github.com/ioniodi/site-gr/pull/22)

**Comment by 0xDockerman** [comment]
@GIANNIS-AGGELIS Για την ακριβεια εγω δεν επεξεργαστηκα τα μαθηματα απο το πρωτο ετος αλλα τα πρωτα 20 μαθηματα με αλφαβητικη σειρα που ηταν στο φακελο `_courses`.
Οποτε υπαρχουν ακομα μαθηματα απο το πρωτο ετος που χρειαζονται επεξεργασια.
