### ISSUE TITLE
Ενημέρωση και προσθήκη νέων σελίδων για τους διδάσκοντες, τα μαθήματα, τα εργαστήρια και για τα ερευνητικά προγράμματα

### ISSUE THREAD

**Issue by KonstantinosG** [ioniodi/site-gr#33]
Ενημέρωση σελίδων για τα μαθήματα του δεύτερου ακαδημαϊκού έτους.

**Comment by epidrome** [comment]
προσοχή στα παρακάτω:

1. ίσως να έχουν γίνει κάποια ήδη αλφαβητικά
2. να είσαι σε συγχρονισμό με το κεντρικό στο οποίο γίνονται συνέχεια προσθήκες
