### ISSUE TITLE
Social Media Integration

### ISSUE THREAD

**Issue by ghost** [ioniodi/site-gr#44]
Κατά 90% θα χρειαστεί να γίνουν αλλαγές και στο αποθετήριο του θέματος minimal-ionio καθώς εκεί βρίσκεται ο φάκελος με τα includes. Θα προσπαθήσω να δουλέψω τοπικά για αρχή.

**Comment by ghost** [comment]
Οι αλλαγές στο αποθετήριο του θέματος: https://github.com/ioniodi/minimal-ionio/pull/12

![google+changes](https://user-images.githubusercontent.com/11950996/75925784-02886f80-5e72-11ea-86ab-585096a0708b.PNG)

![facebook-href-temporary-fix](https://user-images.githubusercontent.com/11950996/75925790-04eac980-5e72-11ea-99e4-b549b00fb29b.PNG)

![google+](https://user-images.githubusercontent.com/11950996/75925874-26e44c00-5e72-11ea-8e7c-fed15da6a0a3.PNG)
![google+changes](https://user-images.githubusercontent.com/11950996/75925878-28157900-5e72-11ea-89ba-4505a2a6ca13.PNG)
![facebook-href-temporary-fix](https://user-images.githubusercontent.com/11950996/75925881-28ae0f80-5e72-11ea-995c-529143871ffa.PNG)

**Comment by epidrome** [comment]
το θέμα θέλει αρκετή συζήτηση-σκέψη, καλύτερα από κοντά

στο μεταξύ λίγα σχόλια

1. η ενεργοποίηση των κουμπιών γίνεται από το config.yml
2. το βασικό θέμα έχει ενημερωθεί αλλά το μίνιμαλ-ιόνιο δεν έχει και σίγουρα δεν είναι καλή ιδέα να κάνουμε αλλαγές που έχει κάνει το αρχικό, άλλωστε υπάρχει ανοικτό θέμα για ενημέρωση του μινιμαλ-ιόνιο

αν δεν κάνω λάθος στα παραπάνω το θέμα αυτό μάλλον πρέπει να κλείσει..

**Comment by ghost** [comment]
>  άλλωστε υπάρχει ανοικτό θέμα για ενημέρωση του μινιμαλ-ιόνιο
Όντως νομιζω το update του θέματος θα λύσει το πρόβλημα οπότε το κλείνω για τωρα.
