### ISSUE TITLE
Προσθήκη κατευθύνσεων και μαθημάτων μεταπτυχιακών σπουδών

### ISSUE THREAD

**Issue by provopoulos** [ioniodi/site-gr#47]
+ αλλαγές/ενημερώσεις σε όσα αρχεία χρειάζονται.

**Comment by epidrome** [comment]
καλύτερα θα ήταν να εστιάσεις στο προπτυχιακό σε ένα εξάμηνο-έτος, π.χ., #34 #33 

αν θες άλλαξε τίτλο και σχόλιο και ενημέρωσε με ώστε να γίνει δεκτό

**Comment by provopoulos** [comment]
Οι συγκεκριμένες προσθήκες παρουσιάζουν την εξής ιδιαιτερότητα:
http://di.ionio.gr/postgraduate-studies/
Μερικά μαθήματα των ΠΜΣ διαφέρουν ανάλογα την κατεύθυνση επομένως ο τρόπος υλοποίησης του μενού: https://vibrant-haibt-349f89.netlify.com/courses/ πρέπει να τα διαχωρίζει.
Έχω μια ιδέα για πιθανή υλοποίηση ωστόσο πρέπει να καλύψω τουλάχιστον 2 εξάμηνα (π.χ. χειμερινά) ανά κατεύθυνση ώστε να μπορέσω να διαπιστώσω αν λειτουργεί αυτό που σκέφτομαι.

**Comment by provopoulos** [comment]
Ένα πρόχειρο LIVE DEMO: https://gracious-pare-5d2c81.netlify.com/courses/
Φωτογραφία: https://imgur.com/a/EtOoxMr
Στην ουσία πρόκειται για διαχωρισμό των μεταπτυχιακών εξαμήνων ανάλογα με την κατεύθυνση.

**Comment by provopoulos** [comment]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{% include collection-sort.html i = 11 l = 'msc' %}
&&
{% include collection-sort.html i = 21 l = 'msc' %}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Είναι οι αλλαγές. Στο πρόχειρο παράδειγμα παραπάνω στα 2 μαθήματα έγινε αλλαγή του πεδίου εξαμήνου από 1 σε 11 και από 2 σε 22.
Όπου 11 -> 1: για πρώτη κατεύθυνση και 1: για πρώτο εξάμηνο.
21 -> 2: δεύτερη κατεύθυνση και 1: πρώτο εξάμηνο
(https://github.com/provopoulos/site-gr/blob/test/_msc/adm-inf-systems.md && https://github.com/provopoulos/site-gr/blob/test/_msc/ai.md)

**Comment by provopoulos** [comment]
Δεν θεωρώ πως είναι απαραίτητα QOL ο τρόπος υλοποίησης της ιδέας αλλά την θεωρώ γενικά καλή ως ιδέα (να υπάρχει δηλαδή διαχωρισμός εξαμήνων ανά κατεύθυνση).

**Comment by provopoulos** [comment]
Any remarks? @jimDragon

**Comment by epidrome** [comment]
όπως είπαμε και στα δύο πρώτα μαθήματα, και όπως γράφει και στην εισαγωγή του roadmap:

σε αυτήν την 1η φάση "ζεστάματος" με πολύ εύκολα ζητούμενα καλό είναι να μην ασχοληθούμε με κώδικα, αλλά να κάνουμε λίγο σκούπισμα-ξεσκόνισμα

το θέμα εδώ είναι πολύ ενδιαφέρον και πολύπλοκο επομένως (όπως έχουμε πει) καλό είναι να συζητηθεί δια ζώσης και όχι εδώ
