### ISSUE TITLE
Δημιουργία αρχείου για θέματα-ερωτήματα

### ISSUE THREAD

**Issue by korinaal** [ioniodi/site-gr#57]
Θα δημιουργήσω ένα αρχείο με σκοπό να βοηθήσω τον maintainer και τον φοιτητή, κατά τη δημιουργία νέων θεμάτων/ερωτημάτων.

**Comment by korinaal** [comment]
@epidrome @constantinexisc Θα ήθελα να σας ρωτήσω πως θα σας φαινόταν αν πρόσθετα ένα ακόμη label για τα θέματα που αναμένουν το green light, ώστε να ξεχωρίζουν καλύτερα στη λίστα με τα ανοιχτά issues; Αν συμφωνείτε, τι θα λέγατε να το συμπεριλάβω στο αρχείο για θέματα-ερωτήματα που έχω αναλάβει;

**Comment by epidrome** [comment]
https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
