### ISSUE TITLE
Κεντρικός φάκελος για όλες τις συλλογές σύμφωνα με το jekyll 3.7

### ISSUE THREAD

**Issue by p15zerv** [ioniodi/site-gr#58]
Δημιουργία ενός κεντρικού φακέλου που να περιέχει όλα τα collections, σύμφωνα με τις [αλλαγές του Jekyll 3.7](https://jekyllrb.com/news/2018/01/02/jekyll-3-7-0-released/) και συγκεκριμένα την προσθήκη του `collections_dir: <collection_path>`.

__Να σημειωθεί__ πως, λόγω του γεγονότος ότι όλα τα υπάρχοντα collections θα μετακινηθούν, ο αριθμός των αλλαγών στο commit αναμένεται να είναι πολύ ύψηλος. Θα δημιουργθεί πρόβλημα;

**Comment by ghost** [comment]
Δεν νομίζω να υπάρξει πρόβλημα αφού το commit θα έχει πολύ συγκεκριμένο στόχο, απλά 'move' commits θα είναι δεν θα πειράξεις τα αρχεία. 

Τώρα θα έχουν πρόβλημα όσοι θέλουν να δουλέψουν στα αρχεία και δεν κάνουν update το αποθετήριο τους νομίζω γιατί το git είναι "έξυπνο" αρκετά ώστε να καταλάβει πότε μετακινέις αρχεία, αλλά δεν νομίζω να κάνει το ίδιο το GitHub για pull requests από forks όταν τα αρχεία είναι σε άλλο φάκελο, αλλά αυτό λύνεται.

**Comment by epidrome** [comment]
συμφωνώ φαίνεται ότι είναι εύκολο να γίνει, απλά μεταφορά, ένα ντέμο λινκ θα ήταν χρήσιμο, αν δεν μας αρέσει το κόβουμε.
