### ISSUE TITLE
layout+yaml ερευνητικά προγράμματα ως ανακοινώσεις (start-end date sorting)

### ISSUE THREAD

**Issue by dimpram** [ioniodi/site-gr#59]
Αναλαμβάνω να οργανώσω το collection **" _projects"** και να προστεθούν/παρουσιαστούν ως ανακοινώσεις σε κατάλληλο layout από το minimal-ionio.

**Comment by epidrome** [comment]
αφούς δεις όλα τα μαρκνταουν
ξεκίνα με 2-3 ενδεικτικά και φτιάξε την νέα δομή δεδομένων να την συζητήσουμε λίγο εδώ ή καλύτερα στην συνάντηση πριν κάνεις αίτημα
ευχαριστούμε!

**Comment by dimpram** [comment]
@epidrome Γενικά έψαξα και άλλο το project και παρατήρησα οτι και τα projects παρουσιάζονται ήδη στο site άρα όλα αυτά τα .md αρχεία που βλέπαμε την προηγούμενη φορά χρησιμοποιηούνται. Εντέλει δεν ειμαι σιγούρος αν έχω καταλάβει πιο είναι ακριβώς το ζητούμενο. Επίσης όταν λέτε "νέα δομή δεδομένων" εννοείτε νέο collection? Γιατί αν εννοείτε αυτό πάλι δεν είμαι σίγουρος αν καταλαβαίνω τον λόγο για τον οποίο πρέπει να γίνει αυτό.

**Comment by epidrome** [comment]
νέα δομή δεδομένων σημαίνει π.χ., αν είναι τύπου ποστ ότι ο τίτλος θα πρέπει να έχει ημερομηνία π.χ., έναρξης ή τέλους, δλδ κάτι απλό αλλά σίγουρα θέλει σκέψη-συζήτηση

**Comment by dimpram** [comment]
# Πρόοδος
Τελικά με λίγο παραπάνω ψάξιμο στον κώδικα κατάφερα να διαχειριστώ το projects collection σαν posts.

## Λεπτομέρειες
Πρόσθεσα στην ονομασία του αρχείου μια (προς το παρόν ενδεικτική) ημερομηνία και τα εμφανίζω σύμφωνα με τα built-in layouts του minimal-ionio, archive.

Θα ήθελα να μου πείτε αν συμφωνείτε με το παρουσιαστικό που φαίνεται εδώ:

![Screenshot from 2020-03-28 16-09-26](https://user-images.githubusercontent.com/44473195/77824905-94506900-710e-11ea-8ce8-c0f5a3d639b2.png)

@epidrome
