### ISSUE TITLE
προσθήκη link σε σελίδα καθηγητή από το μάθημα του

### ISSUE THREAD

**Issue by 0xDockerman** [ioniodi/site-gr#60]
Στην σελιδα των μαθηματων εμφανιζεται ο καθηγητης του μαθηματος αλλα δεν εχει την δυνατοτητα να ανακατευθύνετε στην σελιδα του
![Image](https://i.imgur.com/G5d2qgA.png)

**Comment by ghost** [comment]
Εγώ που δοκίμασα 3 καθηγητές (Βλάμος, Οικονόμου, Μυλωνάς) με έβγαλε σωστά στις:
https://eliki.ionio.gr/~okon/
http://image.ntua.gr/~fmylonas/
https://eliki.ionio.gr/~okon/

Που ειναι οι σελιδες των αντίστοιχων καθηγητων.

**Comment by 0xDockerman** [comment]
@constantinexisc Θα να κανω μια διευκρινηση λογω παραλειψης μου
Οταν εννουσα στις σελιδες τους υπονοουσα την σελιδα στο collection `_people`  και οχι την προσωπικη τους

Αρα οταν καποιος θα πλοηγειται στην σελιδα ενος μαθηματος και θα βλεπει στα αριστερα τα στοιχεια του καθηγητη, θα πατας την εικονα ή το ονομα του καθηγητη θα μεταφερεσαι στην σελιδα του
