### ISSUE TITLE
 Αρχιτεκτονική της πληροφορίας για τις ανακοινώσεις (κατηγορίες, ετικέτες)

### ISSUE THREAD

**Issue by andreanastil** [ioniodi/site-gr#63]
2η Λίστα Καινούργια 
@epidrome τι λέτε; συμβουλέυτηκα και το κεντρικό site του πανεπιστημίου
 
Categories:
- ΣΠΟΥΔΕΣ
- ΕΚΔΗΛΩΣΕΙΣ
- ΔΙΑΓΩΝΙΣΜΟΙ- ΠΡΟΚΗΡΥΞΕΙΣ
- ΑΝΑΚΟΙΝΩΣΕΙΣ

Tags:
- Προπτυχιακές Σπουδές
- Μεταπτυχιακές Σπουδές
- Διδακτορικά (new)
- Συγγράματα (new)
- Πρόγραμμα Μαθημάτων
- Πρόγραμμα Εξετάσεων
- Erasmus
- Πρακτική Άσκηση Erasmus
- Πρακτική Άσκηση
- Υποτροφίες 
- Θερινά Σχολεία
- Συνέδρια
- Ομιλίες
- Γενικές Εκδηλώσεις
- Ανασκοπήσεις Εκδηλώσεων
- Προκηρύξεις
- Γενικοί Διαγωνισμοί
- Προσκλήσεις Προσφορών
- Εκλογές Καθηγητών
- Εγκρίσεις και Αποτελέσματα
- Γενικές Ανακοινώσεις
- Αποφάσεις Οργάνων
- Φοιτητικά Έργα και Νέα
- Σίτιση
- Στέγαση
- Εκδόσεις
- Γραμματεία
- Δελτία Τύπου
- Newsletter
- Έρευνα
- Δραστηριότητες Μελών

**Comment by epidrome** [comment]
μερικές ιδέες:

1. θα βοηθούσε να δεις 5-10 ανακοινώσεις από διαφορετικά είδη, π.χ., συνέδριο, γραμματεία, ομιλητής, κτλ
 
2. φτιάξε μια μικρή λίστα με κατηγορίες και ετικέτες να την συζητήσουμε λίγο εδώ ή καλύτερα στην συνάντηση πριν κάνεις αίτημα

3. κάλεσε (mention) 1-2 συναδέλφους για σχολιασμό εδώ

4. documentation
https://jekyllrb.com/docs/front-matter/#predefined-variables-for-posts
https://jekyllrb.com/tutorials/navigation/#scenario-8-retrieving-items-based-on-front-matter-properties

ευχαριστούμε!

**Comment by andreanastil** [comment]
Έπείτα από μια επισκόπηση των ανακοινώσεων του τωρινού σαιτ, μπορώ να προτείνω τις εξής κατηγορίες: 

Σεμινάρια
Εκλογές
Συνεδριο
Ομιλία
Erasmus
Εκδήλωση
Πρακτική Άσκηση
Συνέλευση
Έργο
Μαθήματα Προπτυχιακού
Μεταπτυχιακά

**Comment by andreanastil** [comment]
Έπείτα από μια επισκόπηση των ανακοινώσεων του τωρινού σαιτ, μπορώ να προτείνω τις εξής κατηγορίες:

Σεμινάρια
Εκλογές
Συνεδριο
Ομιλία
Erasmus
Εκδήλωση
Μαθήματα Προπτυχιακού
Μεταπτυχιακά
Πρακτική Άσκηση

**Comment by andreanastil** [comment]
Έπείτα από μια επισκόπηση των ανακοινώσεων του τωρινού site, προτείνω τις εξής κατηγορίες:

- Γραμματεία
- Σεμινάρια
- Εκλογές
- Συνέδριο
- Ομιλία
- Συνέλευση
- Έργο
- Erasmus
- Εκδήλωση
- Ημερίδα
- Προπτυχιακό
- Μεταπτυχιακά
- Πρακτική Άσκηση
- Πρόγραμμα Εξεταστικής
- Αναβολή Μαθήματος
- Παρατάση (όποιου είδους)
- Διαγωνισμός
- Προκήρυξη

Μία ανακοίνωση, ενδεχόμενα, θα μπορεί να ανήκει σε παραπάνω από μία κατηγορία.

@epidrome Μπορείτε να διευκρινίσετε εάν μια κατηγορία αντιστοιχεί και σε μια ετικέτα;

Παρακαλώ τους συναδέλφους @korinaal @p15zerv να πούνε την άποψή τους.

**Comment by korinaal** [comment]
@epidrome @andreanastil @p15zerv θα πρότεινα να προστεθεί μια ακόμη κατηγορία "Προκηρύξεις" για εκλογές, Προγράμματα Μεταπτυχιακών Σπουδών κ.ά.

Ευχαριστώ :)

**Comment by andreanastil** [comment]
@korinaal Ναι, αμέ, συμφωνώ και εγώ σε αυτό. Την προσθέτω

**Comment by p15zerv** [comment]
Αρκετά εκτενής λίστα, με μια γρήγορη περασία στο υπάρχον site φαίνεται να καλύπτει τις περισσότερες ανακοινώσεις. Από όσο είδα στο site του τμήματος (di.ionio.gr) υπάρχουν αρκετά λίγες κατηγορίες, με τις περισσότερες ανακοινώσεις να μην ανήκουν σε καμία από αυτές. 

Όμως υπάρχει αρκετά εκτενής λίστα κατηγοριών στο κεντρικό site του πανεπιστημίου (ionio.gr), οπότε ίσως μπορούμε να πάρουμε κάποιες ιδέες από εκεί (έχει μέχρι και για τον Κορωνοϊό!).


https://ionio.gr/gr/news/all-news/

**Comment by andreanastil** [comment]
Αα πολύ καλό αυτό. Θα ρίξω και εγώ μια ματιά!

**Comment by epidrome** [comment]
@andreanastil  ενημερώθηκε το 1ο ποστ με ένα πρώτο διαχωρισμό σε κατηγορίες-ετικέτες με το σκεπτικό ότι για κάθε ανάρτηση:

1. κατηγορίες είναι ο αποστολέας και είναι μοναδικός
2. ετικέτες είναι ιδιότητες που έχει και μπορεί να είναι πολλές

αν θες να το επεξεργαστείς λίγο ακόμη και μετά να περάσουμε στον κώδικα που θα δείχνει και θα επιτρέπει πλοήγηση-φιλτράρισμα με βάση κατηγορίες-ετικέτες από το σημείο 4 στο προηγούμενο σχόλιο

**Comment by epidrome** [comment]
@andreanastil 
στο 1ο ποστ σβήσε τα παλιά, άλλωστε φαίνονται στο ιστορικό για όποιον θέλει να δει και κράτα μόνο την πρόταση σου

αναρωτιέμαι ποιο είναι το σκεπτικό με δύο λόγια; μαντεύω ότι οι κατηγορίες αντί για τον αποστολέα είναι από την πλευρά του χρήστη; 

συμφωνώ, αν θέλει και κάποιος άλλος να μας σχολιάσει

**Comment by andreanastil** [comment]
@epidrome Μάλιστα, από τη πλευρά του χρήστη, και έτσι ετστιάζουν περισσότερο στο περιεχόμενο της κάθε ανάρτησης. Οι μεν ετικέτες, επεκτείνουν τις κατηγορίες και είναι πιο ειδικές. 

@p15zerv @korinaal Πείτε και εσείς τη γνώμη σας εάν θέλετε. 

Οπότε σβήνω την παλιά λίστα.

**Comment by andreanastil** [comment]
Έχει γίνει pull request
