### ISSUE TITLE
Συντομεύσεις πλοήγησης με την οργάνωση και τις βασικές σελίδες

### ISSUE THREAD

**Issue by AsteriosP** [ioniodi/site-gr#67]
Αν κατάλαβα σωστά θέλουμε στο χάρτη πλοήγησης για τον χρήστη να έχει μόνο τις  
 - βασικές σελίδες (Προσωπικό, Σπουδές, Εργαστήρια, Ανακοινώσεις, κτλ) 
 - και όταν λέει οργάνωση την δενδρική δομή του site; 
θέλω κάποιο input, ευχαριστώ.

**Comment by epidrome** [comment]
ποιες σελίδες θα προσθέσουμε; καπου 20 για αρχή;

καλό θα ήταν να σχολιάσουν και 2-3 από την ομάδα

επίσης καλό θα ήταν να έχουμε 3-4 παραδείγμα σελίδων από άλλού ώστε να δούμε πως το οργανώνουν

**Comment by epidrome** [comment]
@AsteriosP 
πριν γίνει αίτημα ενσωμάτωσης αν θες να απαντήσεις στο παραπάνω ποστ και να καλέσεις κάποιους

μερικές ακόμη ιδέες μετά το χθεσινό ντέμο:

1. η επιλογή σελίδων θα μπορούσε να προκύψει από το τοπ5-10 της επισκεψιμότητας

2. το αρχείο navigation.yml καλύτερα να μείνει καθαρό γιατί είναι του minimal-mistakes, μάλλον καλύτερα είναι να έχουμε ένα νέο αρχείο, π.χ., shortcuts.yml

**Comment by AsteriosP** [comment]
@p15zerv  @KonstantinosG  @korinaal @NikosAvg 
θα ήθελα να πείτε άποψη με τον παρακάτω χάρτη πλοήγησης. Ποιές σελίδες προτείνετε να βάλουμε στον παρακάτω χάρτη πλοήγησης;
| Προσωπικό | Μαθήματα Προπτυχιακό | Εργαστήρια | Χρήσιμοι Σύνδεσμοι |
|---|---|---|---|
| Βασίλειος Χρυσικόπουλος  | Α' Εξάμηνο  | BIHELab | Ionio Open eClass |
| Παναγιώτης Βλάμος  | Β' Εξάμηνο  | CMODLab | WebMail |
| ... | ... | ... | ... |

Η δομή του χάρτη πλοήγησης θα μπει το αρχείο `/_data/shortcuts.yml` του αποθετηρίου του site-gr

Μερικά παραδείγματα από χάρτες πλοήγησης:
- [Unity](https://unity.com/)
- [Ubuntu](https://ubuntu.com/)
- [Πανεπιστήμιο του  Cambridge](https://www.cam.ac.uk/): [Computer Science and Technology](https://www.cst.cam.ac.uk/)
- [New York University](https://www.nyu.edu/)

**Comment by NikosAvg** [comment]
@AsteriosP Δεν ξέρω αν υπάρχει τρόπος να δούμε τις σελίδες με την περισσότερη επισκεψιμοτητα άλλα θα μπορούσαμε να βάλουμε λινκ που να πηγαίνουν στα προγράμματα προπτυχιακό/μεταπτυχιακό, στα ερευνητικά εργαστήρια και ίσως στις πιο χρήσιμες υπηρεσίες για φοιτητηες

**Comment by epidrome** [comment]
@AsteriosP 
1.άλλαξα τον τίτλο σε συντομεύσεις πλοήγησης γιατί φαίνεται με κάτι τέτοιο ασχολούμαστε

2. οι ιδρυματικές σελίδες δεν βοηθάνε στις ιδέες θα θέλαμε κάποιο τμήμα

3. θα ψάξω για την επισκεψιμότητα

**Comment by epidrome** [comment]
μια ακόμη ιδέα για την λίστα με τις "συντομεύσεις" θα είναι να έχουμε μερικές σημαντικές κατηγορίες ή/και ετικέτες από τις ανακοινώσεις #63 π.χ., γραμματεία, σίτιση, στέγαση, κτλ

**Comment by epidrome** [comment]
επισυνάπτω μια λίστα για τις σελίδες με 100 τουλάχιστον κλικ από την αναζήτηση του γκουγκλ για την κανονική σελίδας του τμήματος τα τελευταία 3 χρόνια, 

νομίζω είναι ενδεικτική, σίγουρα δεν είναι 100% ακριβής, αφού η επίσκεψη σε μια σελίδα μπορεί να γίνεται και από άλλα μέσα, πχ. φειςμπουκ, απευθείας

[http___di.ionio.gr_-Performance-on-Search-2020-04-07.pdf](https://github.com/ioniodi/site-gr/files/4450069/http___di.ionio.gr_-Performance-on-Search-2020-04-07.pdf)
