### ISSUE TITLE
 Προσθήκη χάρτη και σύνδεση με την εφαρμογή πλοήγησης στο κινητό του χρήστη

### ISSUE THREAD

**Issue by KonstantinosG** [ioniodi/site-gr#69]
Κυρίως βήματα προς υλοποίηση:
- [x] Προσθήκη στο κάτω μέρος της αρχικής σελίδας ένα (ενδεχομένως) τετράγωνο πλαίσιο το οποίο θα εμφανίζει τον χάρτη.
- [x] Προσθήκη των συντεταγμένων εντός του χάρτη και δημιουργία ενός pin το οποίο θα υποδεικνύει την τοποθεσία του Τημήματος Πληροφορικής.
- [ ] Προσθήκη ενός κουμπιού το οποίο θα ανοίγει εξωτερική εφαρμογή πλοήγησης (από το κινητό του χρήστη ή τον υπολογιστή) στην οποία θα μεταφέρονται οι συντεταγμένες.

**Comment by epidrome** [comment]
consider open street maps leaflet

**Comment by KonstantinosG** [comment]
Τα πρώτα δύο βήματα έχουν ολοκληρωθεί επιτυχώς. Για τις ανάγκες της ιστοσελίδας αποφάσισα να ακολουθήσω την πρότασή σας σχετικά με το open street maps leaflet. Έτσι, έχει αφαιρεθεί πλέον κάθε αναφορά στον κώδικα σχετικά με τα Google Maps. Το branch μου περιέχει τον κώδικα με τον οποίο ενσωματώνεται το leaflet στην αρχική σελίδα του website. 
Αναφορικά με το τρίτο βήμα:
Προσπάθησα να τρέξω την ιστοσελίδα από το κινητό μου χρησιμοποιώντας το λινκ του netlify αλλα δεν είχα ιδιαίτερη επιτυχία. Ενδέχεται να μην έχει προλάβει να δει τις αλλαγές ακόμα καθώς οι τελευταίες ανέβηκαν σχετικά πρόσφατα στο repo μου. Θα προσπαθήσω εκ νέου αργότερα.

**Comment by epidrome** [comment]
μερικά σχόλια για τις προδιαγραφές στο 1ο ποστ:

1. ο χάρτης να είναι σε μια σελίδα ξεχωριστή σελίδα επικοινωνίας και όχι στην αρχική, έτσι συνήθως γίνεται

2. το τμήμα έχει πολλές θέσεις στην πόλη, καλό θα ήταν να φαίνονται όλες

**Comment by KonstantinosG** [comment]
Νέες αλλαγές και προσθήκες:

1. Έχει δημιουργηθεί νέα σελίδα με στοιχεία επικοινωνίας (αυτά προέρχονται από τη σελίδα του τμήματος που βρίσκεται εν ενεργεία)
2. Έγινε προσθήκη επιπλέων marker εντός του χάρτη για τις εξής τοποθεσίες: Κτίριο Αρεταίος, Κτίριο Γαληνός, Κτίριο Γραμματειών, Φοιτητική Λέσχη, Τμήμα Ιστορίας (για τα αμφιθέατρα όπου γίνονται μαθήματα), Γραφεία καθηγητών Ανάκτορα, Ιόνιος Ακαδημία

Σχετικά με την πλοήγηση του χρήστη από το κινητό κατάφερα να τρέξω την ιστοσελίδα μέσω του Netlify από το κινητό μου αλλά δεν έχω βρει τρόπο να επιλέγεις πινέζα και να σε πετάει στον χάρτη του κινητού για πλοήγηση.

Σημείωση: To πρόβλημα με το Netlify ήταν ότι είχα αλλάξει το branch το οποίο έκανε compile αλλά δεν μπορούσε να το τρέξει επειδή μετά την αλλαγή του δεν είχα κάνει κάποιο push για να το τρέξει.

**Comment by p15zerv** [comment]
Για να καταγραφεί κι εδώ, ίσως είναι καλή ιδέα η σελίδα με το χάρτη και τα στοιχεία επικοινωνίας να προστεθούν στο #67 

Κατά τα άλλα φαίνεται να είναι σε πολύ καλό σημείο
