### ISSUE TITLE
migration to jekyll 4+

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#70]
check for possible errors before migrating to jekyll4+

**Comment by ghost** [comment]
Θα το κοιταξω αυτό παράλληλα με το αλλο που εχω παρει για το ιστορικο.

**Comment by epidrome** [comment]
το δοκίμασα τοπικά και φαίνεται δουλεύει χωρίς πρόβλημα, 
αλλά πριν το ενσωματώσουμε ας ζητήσουμε από μερικούς ακόμη να το δοκιμάσουν
@GIANNIS-AGGELIS @jimDragon @provopoulos

**Comment by dimpram** [comment]
Εμένα μου πετάει κάποια warnings μερικά από τα οποία μου τα εμφάνιζε και πριν. Ενδεχομένως να είναι πρόβλημα στο σύστημά μου και όχι σε εσάς. Όπως και να έχει το αναφέρω σε περίπτωση που κάποιος αντιμετοπίζει το ίδιο:

```
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/convertible.rb:41: warning: Using the last argument as keyword parameters is deprecated
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:466: warning: Using the last argument as keyword parameters is deprecated
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:432: warning: Passing the keyword argument as the last hash parameter is deprecated
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:75: warning: The called method `merge_data!' is defined here
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/document.rb:439: warning: Passing the keyword argument as the last hash parameter is deprecated
.gem/ruby/2.7.0/gems/jekyll-4.0.0/lib/jekyll/tags/include.rb:179: warning: Using the last argument as keyword parameters is deprecated
```
(Κάπου [εδώ](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/) πρέπει να είναι και η λύση)

Επιπλέον εμφανίζονται αυτά εδώ τα errors εδώ και αρκετό καιρό βέβαια είναι απλά κάποια png:

```
[2020-04-03 16:33:09] ERROR `/assets/images/mm-customizable-feature.png' not found.
[2020-04-03 16:33:09] ERROR `/assets/images/mm-responsive-feature.png' not found.
[2020-04-03 16:33:09] ERROR `/assets/images/mm-free-feature.png' not found.
[2020-04-03 16:33:09] ERROR `/favicon-32x32.png' not found.
[2020-04-03 16:34:54] ERROR `/favicon-32x32.png' not found.
[2020-04-03 16:34:56] ERROR `/favicon-32x32.png' not found.
```
Kατά τα άλλα μου τρέχει μια χαρά.

**Comment by ghost** [comment]
@jimDragon  

Απο οτι βλεπω τα warnings σου ειναι εξαιτιας του οτι τρεχεις ruby 2.7 που ειναι προετοιμασια για την 3.0 που θα ερθει πιο μετα στο τελος του 2020 η αρχη 2021. Εχουν βαλει τα warnings στην 2.7 για να αλλαξει ο κωδικας που θα εχει προβλημα οταν κανουν upgrade στην 3.0, αλλα για τωρα θα δουλευει κανονικα. Εγω που τρεχω 2.5 δεν μου βγαζει τιποτα φυσικα.

Αυτο ειναι προβλημα του Jekyll που θα πρεπει να το αλλαξουν οι devs του jekyll για την ruby 3.0 δεν νομιζω να επηρεαζει τιποτα για το δικο μας site για τουλαχιστον 1,5+ χρονο ακομη.

**Comment by epidrome** [comment]
@constantinexisc @jimDragon @GIANNIS-AGGELIS 
μήπως είναι ευκαιρία να προσθέσουμε στο `.ruby-version` την έκδοση που θέλουμε?

τώρα έχει την 2.6.2 την οποία έτυχε να έχω στο σύστημα μου, αλλά δεν το έχω ψάξει περισσότερο αν αυτή είναι η βέλτιστη για την τρέχουσα έκδοση του jekyll

άνοιξα νέο σχετικό θέμα #92
