### ISSUE TITLE
Οργάνωση των μαθημάτων κορμού-επιλογής-κατεύθυνσης

### ISSUE THREAD

**Issue by korinaal** [ioniodi/site-gr#71]
Θα αναλάβω να οργανώσω τα μαθήματα ανάλογα με την κατηγορία στην οποία ανήκουν, συμπληρώνοντας μαθήματα  στην κατηγορία των μαθημάτων κατεύθυνσης (μιας και στο site ήδη παρέχεται μια τέτοια είδους κατηγοριοποίηση) και δημιουργώντας από την αρχή τις κατηγορίες μαθημάτων κορμού και επιλογής.

**Comment by epidrome** [comment]
μερικές ιδέες-σχόλια:

1. στο σχετικό αρχείο στο αποθετήριο υπάρχει χρήσιμος κώδικας 
https://github.com/ioniodi/site-gr/blob/master/all_collections/_pages/humanistic.html

2. ίσως η ιδιότητα type να πρέπει να κωδικοποιηθεί κάπως καλύτερα, πχ. H = humanistic, Ο = option, etc.

3. για να είμαστε συνεπείς με τον διαχωρισμό κώδικα-δεδομένων αυτά τα αρχεία θα έπρεπε να είναι στο αποθετήριο του θέματος
