### ISSUE TITLE
Dynamic retrieval of book data from eudoxus

### ISSUE THREAD

**Issue by p15zerv** [ioniodi/site-gr#74]
### Δήλωση Θέματος
- Τίτλος: Dynamic retrieval of book data from eudoxus
- Θα αλλάξω τον τρόπο που εμφανίζονται και ανακτώνται οι πληροφορίες σχετικά με τη βιβλιογραφία κάθε μαθήματος, ώστε αυτό να γίνεται δυναμικά από τον Εύδοξο. Για την ολοκλήρωση αυτού, θα υπάρξει συνεργασία και συνεννόηση με το θέμα #38.
- Δυσκολία Θέματος:  Δύσκολο

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request έχω πάρει το "πράσινο φως"

**Comment by epidrome** [comment]
πριν δούμε κάποιο αίτημα θα ήταν χρήσιμο να δούμε εναλλακτικές τεχνολογίες και παραδείγματα, π.χ., όπως το έχει η wikipedia και να γίνει συζήτηση παρακάτω

**Comment by p15zerv** [comment]
Θα ήθελα να αναλάβω εξ ολοκλήρου και τη μετατροπή από την παλαιά δομή για τη βιβλιογραφία στην καινούρια που πρόσθεσε ο @GIANNIS-AGGELIS στο #80. Η μετατροπή θα γίνει δυναμικά μέσω κάποιου script.

Θεωρώ πως ταιριάζει με το περιεχόμενο του issue. Εφόσον συμφωνείτε, μπορώ να αλλάξω και τον τίτλο για να είναι ξεκάθαρο και στους υπόλοιπους που συνεισφέρουν.

**Comment by epidrome** [comment]
τι εννοείς; η μεταφορά είναι κυρίως "σκούπισμα"-πολύ εύκολο, φυσικά να κάνεις μερικά αν το θες, το λέω γιατί θέλω να δώσεις προτεραιότητα στα εύκολα-δύσκολα

**Comment by p15zerv** [comment]
Σε αναμονή μέχρι να προχωρήσει το #96

**Comment by p15zerv** [comment]
Bump.

Ίσως θα ήταν καλύτερη ιδέα να μαρκάρει το bot θέματα ως stale κάθε δύο εβδομάδες;

**Comment by p15zerv** [comment]
Θεωρώ πλέον, με την ενσωμάτωση του #119, πως δεν είναι τόσο απαραίτητο το συγκεκριμένο θέμα. Επομένως, προσωπικά δεν έχω πρόθεση να το συνεχίσω, μιας και είμαι λίγο αδύναμος σε css και θέματα εμφάνισης. Αλλάζω τα labels σε περίπτωση που θέλει άλλος να το αναλάβει.

Τεκμηρίωση γιατί δεν το θεωρώ τόσο αναγκαίο:
- Η αρχική ιδέα ήταν να υπάρχει κάποιου είδους popup, όπως το wikipedia εμφανίζει αντίστοιχα σε mouseover από άλλα θέματα που αναφέρονται στην σελίδα. 
- Στην περίπτωση του wikipedia, αυτό έχει νόημα διότι υπάρχει μεγάλο πλήθος αναφορών, οι οποίες περιέχουν πολύ περιεχόμενο, οπότε αποφεύγεται η συνεχής μετάβαση του χρήστη σε διαφορετικές σελίδες.
- Στη δική μας περίπτωση, το πολύ να υπάρχουν 3-4 βιβλία ανά μάθημα, με αυτά να έχουν λίγη πληροφορία: ένα πινακάκι και σπάνια μία περιγραφή.
