### ISSUE TITLE
 Δυναμικό περιεχόμενο στην αρχική σελίδα

### ISSUE THREAD

**Issue by Spirosvw** [ioniodi/site-gr#78]

**Comment by epidrome** [comment]
μια αρχική (πρόχειρη) υλοποίηση έχει γίνει εδώ:
https://github.com/mibook/gr/blob/master/index.md

**Comment by Spirosvw** [comment]
@epidrome Σε αυτή την μορφή σας φαίνεται εντάξει? Τα περισσότερα από αυτά περιλαμβάνουν την default εικόνα οπότε δεν την πρόσθεσα. Ενδεικτικό link: https://5e8638abba1c4d4b52381d56--sharp-borg-3fc7ea.netlify.com/
![test](https://user-images.githubusercontent.com/22668228/78290935-361bef80-752d-11ea-86ac-a2358f81a4a1.png)

**Comment by epidrome** [comment]
μπράβο, φαίνεται ωραίο, αρκεί να έχουμε και ένα λινκ για την αντίστοιχη συλλογή, π.χ, προς το σύνολο των ανακοινώσεων

άλλαξα τον τίτλο, ώστε στο μέλλον να ανοίξουμε νέο θέμα για τα πολυμέσα-βίντεο
