### ISSUE TITLE
Αλλαγή πίνακα ιδιοτήτων μαθημάτων ως προς τον τύπο

### ISSUE THREAD

**Issue by korinaal** [ioniodi/site-gr#79]
### Δήλωση Θέματος
- Τίτλος: Αλλαγή πίνακα ιδιοτήτων μαθημάτων ως προς τον τύπο
- Αλλαγή στις σελίδες των μαθημάτων για τον πίνακα με τις ιδιότητες του μαθήματος, ώστε να φαίνεται ο τύπος του μαθήματος με μια λέξη αντί για τον κωδικό.
- Δυσκολία Θέματος: Δεν συμπεριλαμβάνεται στα υπάρχοντα

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request έχω πάρει το "πράσινο φως"

**Comment by epidrome** [comment]
νομίζω είναι σχετικά εύκολο, μάλλον θέλει ένα σετ από ΙΦ στο μινιμαλ-ιονιο
ευχαριστώ!

**Comment by korinaal** [comment]
@epidrome έχω ολοκληρώσει τις απαιτούμενες αλλαγές και έχω προχωρήσει [σε PR στο minimal-ionio. ](https://github.com/ioniodi/minimal-ionio/pull/17) Ευχαριστώ πολύ!
