### ISSUE TITLE
Ενημέρωση και προσθήκη μαθημάτων μεταπτυχιακών σπουδών

### ISSUE THREAD

**Issue by provopoulos** [ioniodi/site-gr#81]
### Δήλωση Θέματος
- Τίτλος επιλεγμένου θέματος
- Σύντομη περιγραφή των επικείμενων αλλαγών
- Δυσκολία Θέματος: Πολύ εύκολο, Εύκολο, Δύσκολο, Πολύ Δύσκολο

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request έχω πάρει το "πράσινο φως"

**Comment by epidrome** [comment]
τα μαθήματα που υπάρχουν ήδη στον φάκελο είναι από το παλιό ΜΠΣ και θέλουν σημαντικές αλλαγές

**Comment by provopoulos** [comment]
Τα μεταπτυχιακά προγράμματα έχουν μαθήματα επιλογής;
Αν ναι, γνωρίζει κάποιος ποια είναι εξ' αυτών;
http://di.ionio.gr/pms-rds/wp-content/uploads/2019/10/%CE%A0%CE%B5%CF%81%CE%B9%CE%B3%CF%81%CE%B1%CF%86%CE%AD%CF%82-v2.pdf

**Comment by epidrome** [comment]
όλα είναι επιλογής, διαλέγουν 5

**Comment by provopoulos** [comment]
Έκλεισα το προηγούμενο PR και άνοιξα νέο ώστε να διορθώσω τα μαθήματα από υποχρεωτικά σε επιλογής.
Ακόμη, χρειάστηκε μια μικρή τροποποίηση στο αρχείο [courses.md](https://github.com/provopoulos/site-gr/blob/gh-pages/all_collections/_pages/courses.md) ώστε να εμφανίζονται σωστά οι αλλαγές @korinaal.
**DEMO:** https://cranky-kare-7c8c65.netlify.com/courses/
Με την σύμφωνη γνώμη όλων, το PR είναι έτοιμο προς ενσωμάτωση.
