### ISSUE TITLE
Help: Local setup του minimal-ionio

### ISSUE THREAD

**Issue by dimpram** [ioniodi/site-gr#82]
## Local setup του minimal-ionio
Αντιμετοπίζω προβλήματα στην προσπάθεια μου να εισάγω ως theme το τοπικό fork μου του minimal-ionio στο επίσης τοπικό fork μου του site-gr ώστε να μπορώ να βλέπω οτι αλλαγές κάνω στο minimal-ionio απευθείας στον υπολογιστή μου.

Τι ακριβώς πρέπει να αλλάξω πέρα από το remote_theme: ionoidi/minimal-ionio για να δουλέψει τοπικά? Αυτό που κάνω είναι:

```
1. Αλλάζω σε theme: "path του τοπικού repo μου" στο config
2. Τρέχω μια φορά το bundle
3. Τρέχω bundle exev jekyll serve
```

και έχω error οτι δεν αναγνωρίζει το theme

**Comment by ghost** [comment]
**Αναλογα με το αν θελεις να κανεις και να προτεινεις αλλαγες (pull request) στο minimal-ionio** θα σου προτεινα να κανεις fork, μετα clone σε τοπικο αποθετηριο, έπειτα κανεις τις αλλαγες που θελεις τοπικα στο minimal-ionio, κανεις push, και μετα bundle exec jekyll serve.

Στο config απλα αλλάζεις το remote-theme από ioniodi/minimal-ionio στο δικο σου jimDragon/minimal-ionio@**branch-name**

Αρα δουλευεις κανονικα και στα δυο αποθετηρια με branches, κανεις τις αλλαγες που θελεις, τσεκαρεις με push, και οταν εισαι ΟΚ κανεις pull request και στα 2 αποθετηρια αν χρειαστει.

**Comment by epidrome** [comment]
@constantinexisc thanks!

νομίζω υπάρχουν και άλλοι τρόποι και για αυτό ζήτησα από τον @jimDragon να τους μελετήσει και να ενημερώσει τα αντίστοιχα αρχεία #87 φυσικά η βοήθεια σου @constantinexisc θα είναι χρήσιμη

**Comment by dimpram** [comment]
@constantinexisc Αυτή είναι η fallback λύση που εντέλει δούλεψα αλλά δυστηχώς οδηγεί σε ένα πολύ χρονοβόρο workflow. Τελικά βρήκα την λύση και θα την ανεβάσω σύντομα στο repository με αφορμή το issue #87 .
