### ISSUE TITLE
Warning: Liquid Warning: Liquid syntax error (line 10): Expected dotdot but found pipe in "{{(page_interests | split: ',' | sort:0) }}" in /_layouts/projects.html

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#89]
Το έτρεξα τοπικά με jekyll 3.8.6, 4.0.0 και βγάζει το μήνυμα του τίτλου

**Comment by dimpram** [comment]
Το διορθώνω

**Comment by dimpram** [comment]
## Solved
@epidrome Το bug βρίσκεται σε αρχείο του minimal-ionio για το οποίο δεν έχω push access οπότε έκανα ένα [pull request](https://github.com/ioniodi/minimal-ionio/pull/16) εκεί. Όταν το κάνετε merge, αυτό το issue μπορεί να κλείσει.
