### ISSUE TITLE
Write access levels: "With great power comes great responsibility"

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#90]
moved to wiki!
https://github.com/ioniodi/site-gr/wiki/Write-access-levels

**Comment by ghost** [comment]
**_"Pushing to master is a symptom"_**

Το ειχα δει παλια καπου γραμμενο και πιστευω οτι ειναι το καλυτερο quote για το 99% των περιπτωσεων δουλευοντας με το git σε ομαδες. Οπως λετε για μικρο-αλλαγες που σιγουρα δεν θα παιξουν ρολο σε κατι δεν υπαρχει προβλημα, για ολα τα αλλα πιστευω τα pull request ειναι μονοδρομος.

**Comment by ghost** [comment]
@epidrome 
Να γραψουμε 2-3 λογια και οδηγιες για το τι σημαινει να εισαι assigned σε pull request, και ο ρολος των reviewers εδω στο issue?

**Comment by epidrome** [comment]
μετά την πρόσφατη εμπειρία: https://github.com/ioniodi/minimal-ionio/pull/18

έγινε αλλαγή στις ρυθμίσεις

για να γίνει αποδεκτό ένα αίτημα απαιτούνται δύο θετικές αξιολογήσεις

ίσως θα πρέπει να ενημερωθούν και κάποια αρχεία #87 

με σύντομες οδηγίες και λινκ σε καλές πρακτικές

π.χ., σε πόσο χρόνο θα πρέπει κάποιος να στείλει αξιολόγηση και να έχουμε απόφαση για (μη) αποδοχή? μια ημέρα ή εβδομάδα? είναι θέμα παραδοχής-συναίνεσης

**Comment by epidrome** [comment]
@constantinexisc 
> Να γραψουμε 2-3 λογια και οδηγιες για το τι σημαινει να εισαι assigned σε pull request, και ο ρολος των reviewers εδω στο issue?

δες το ποστ μου πάνω, καλύτερα σε κάποιο αρχείο #87 ή wiki

**Comment by epidrome** [comment]
@p15zerv έχεις δει την πρόσκληση?
https://github.com/ioniodi/minimal-ionio/invitations

**Comment by epidrome** [comment]
@provopoulos προσπαθησε να γράφεις εντός θέματος #105 
https://github.com/ioniodi/site-gr/invitations

**Comment by p15zerv** [comment]
> @p15zerv έχεις δει την πρόσκληση?
https://github.com/ioniodi/minimal-ionio/invitations

Μόλις το είδα, είχε χαθεί στα πολλά notifications του github. Το invitation είναι πλέον expired, οπότε θα πρέπει να ξαναστείλετε.
