### ISSUE TITLE
Ενημέρωση του minimal-ionio

### ISSUE THREAD

**Issue by dimpram** [ioniodi/site-gr#91]
### Δήλωση Θέματος
- Ενημέρωση του minimal-ionio
- Θα ανανεώσω τo fork "minimal-ionio" ώστε να χρησιμοποιεί την τελευταία έκδοση του minimal-mistakes [4.19.1](https://github.com/mmistakes/minimal-mistakes/releases)
- Δυσκολία Θέματος:  Δύσκολο

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request έχω πάρει το "πράσινο φως"

**Comment by dimpram** [comment]
## Πρόοδος!
Εν τέλει τα κατάφερα να κάνω update το minimal ionio σε βάση minimal mistakes 4.19.1 όπως είχα πει και το έφτασα σε σημείο να δουλεύει όπως θα έπρεπε. Υπάρχουν μερικά θεματάκια περισσότερο οπτικά πχ [ο πίνακας που υπάρχει σε καθε μάθημα είναι λίγο σπασμένος](https://nervous-franklin-0ffe98.netlify.com/courses/linear-algebra/) αλλά δεν έκατσα να ασχοληθώ περαιτέρω ακόμα.

Ωστόσο το έκανα με τον τρόπο του git όπως αναλύει στα [docs](https://mmistakes.github.io/minimal-mistakes/docs/upgrading/) του ο mmistakes. Υπάρχουν και καλά και κακά νέα: 
- Τα **καλά νέα** είναι οτι έγινε η ανανέωση με πολύ κομψό τρόπο.
- Τα **κακά νέα** είναι οτι χρειάστηκε αρκετό manual intervention για να κάνω fix τα **merge conflicts** στα οποία χρειαζόταν να ξέρω τι θέλουμε να κρατήσουμε δικό μας ή να το αλλάξουμε όπως είναι στο default minimal mistakes. Αυτό όμως ήταν μονο για μερικά includes και ήταν περισσότερο το περιενχόμενο τους (links etc) και όχι ο τρόπος λειτουργίας τους οπότε με λίγη προσοχή παραπάνω νομίζω είναι εφικτό. 

Όταν ετοιμάσω το pull request σκέφτομαι να φτιάξω ένα αρχείο "Upgrading notes" το οποίο να περιγράφει συνοπτικά την διαδικασία που ακολούθησα και μερικά notable αρχεία που μου έβγαλαν την ψυχή. 

Προς το παρόν εδώ είναι ένα [**live demo**](https://nervous-franklin-0ffe98.netlify.com/) και θα ήθελα να το εξετάσετε και εσείς(@epidrome @constantinexisc @GIANNIS-AGGELIS και όποιος άλλος) καθώς θα το δουλεύω για να μου πείτε αν βρείτε κάποια περίεργη συμπεριφορά που ενδεχομένως να μην έχω παρατηρήσει ακόμα.

**Comment by epidrome** [comment]
μπράβο!

μήπως η συζήτηση να συνεχίσει εδώ ώστε να είμαστε "επί του θέματος-αποθετηρίου":
https://github.com/ioniodi/minimal-ionio/issues/2
