### ISSUE TITLE
Recommended ruby and jekyll version

### ISSUE THREAD

**Issue by epidrome** [ioniodi/site-gr#92]
Θεωρητικά θα πρέπει να υπάρχει συμβατότητα ανάμεσα σε διαφορετικές εκδόσεις της γλώσσας και του συστήματος, αλλά στην πράξη αυτό δεν συμβαίνει πάντα, ενώ υπάρχουν και διαφορές ανάμεσα σε λειτουργικά συστήματα.

Κρατάμε ανοιχτό αυτό το θέμα και το ενημερώνουμε με την τρέχουσα κατάσταση και συμβουλές-απορίες για αναβαθμίσεις.

**Comment by ghost** [comment]
Ως κανόνα τρέχουμε **Ruby 2.6 και κάτω**, η Ruby 2.7 βγήκε τον Δεκέμβριο του 2019 ενώ το Jekyll 4.0 βγήκε τον Αύγουστο του 2019.

Επίσης η Ruby 2.7 είναι η αρχή των warnings για πιθανά προβλήματα κώδικα στην έκδοση 3.0 στο τέλος του χρόνου. Άρα θα τρομάζουμε κόσμο χωρίς λόγο αν τους λέμε να τρέχουν Ruby 2.7.

Τα προβλήματα με την Ruby 2.7 και 3.0 θα λυθούν με μεταγενέστερη έκδοση του Jekyll (4.1?) και δεν έχει να κάνει με κώδικα στο project μας.

Recommended έκδοση του Jekyll είναι η **4.0** και θα αλλάξει το project σύντομα σε αυτή.

![image](https://user-images.githubusercontent.com/11950996/78836614-24d65580-79fb-11ea-955a-b5b295634955.png)

**Comment by dimpram** [comment]
Μπορούμε να παραμείνουμε προς το παρόν σε Ruby 2.6 αλλά ενδεχομένως να προκύψει κάποιος άλλος (σοβαρότερος) μελλοντικά πχ όταν το jekyll ενδεχομένως κάνει catch up στις αλλαγές μαζί και ο minimal mistakes.

**Comment by ghost** [comment]
Γενικά αυτά τα προβλήματα υπάρχουν πάντα, πχ. το github pages ειναι ακομα στο Jekyll 3.8.5. Το Jekyll 4.0 δεν εχει γινει test πανω στην ruby 2.7 οποτε βγαζει warnings. Το minimal mistakes εχει τα δικα του dependencies, και παει λεγοντας, αρα δεν γλιτωνουμε οτι και να κανουμε. 

Οπως ειπε ο @epidrome μένει το θεμα ανοιχτο για να παρακολουθουμε εδω τα updates απο ruby/jekyll/plugins/minimalmistakes κτλ. και προτεινω να μπουν τα πιο προσφατα recommended versions που τρεχει το site στο readme ωστε να μην χρειαζεται καποιος να μπει στο Gemfile να δει τι Jekyll και τι θεμα τρεχουμε για παραδειγμα..

**Comment by epidrome** [comment]
> Γενικά αυτά τα προβλήματα υπάρχουν πάντα, πχ. το github pages ειναι ακομα στο Jekyll 3.8.5. Το Jekyll 4.0 δεν εχει γινει test πανω στην ruby 2.7 οποτε βγαζει warnings. Το minimal mistakes εχει τα δικα του dependencies, και παει λεγοντας, αρα δεν γλιτωνουμε οτι και να κανουμε.

συμφωνώ, για την ώρα, τοπικά δουλεύω με ρουμπι 2.6.2 και τζεκιλ 3.8.6, 

γενικά οι αναβαθμίσεις σε εκδόσεις Χ.0.0 είναι ρίσκο, 

προτιμώ τις εκδόσεις Χ.2.2+, όταν θα έχουν γίνει αρκετές διορθώσεις

φυσικά υπάρχουν εξαιρέσεις, αν έχουμε να κερδίσουμε κάτι σημαντικό

π.χ., ένα από τα σημαντικότερα για το θέμα στο μινιμαλ-ιονιο αιτήματα είναι σε εκκρεμότητα 2+ χρόνια, για αυτό και μόνο θα έκανα οποιαδήποτε εξαίρεση!!!
https://github.com/jekyll/jekyll/issues/7344

θα ήθελα να έχουμε και την γνώμη όλων των άλλων συνεργατών που έχουν την ευθύνη του θέματος πριν κάνουμε μια τελική σύσταση

**Comment by epidrome** [comment]
θυμίζω πως όταν είστε assign περιμένουμε κάποιο σχόλιο!!!

@p15zerv 
@korinaal 
@GIANNIS-AGGELIS 
@NikosAvg

**Comment by korinaal** [comment]
Θεωρώ πως το update σε jekyll 4.0.0 είναι συμφέρον για το site (π.χ. καλύτερη απόδοση) και δεν παρουσίασε προβλήματα ούτε σε εμένα όταν το δοκίμασα τοπικά. Αναφορικά τώρα με τη ruby, σε περίπτωση που πετάει πολλά warnings η έκδοση 2.7 (όπως ανέφερε και ο @constantinexisc), μάλλον είναι καλύτερο να ακολουθήσουμε τον κανόνα 2.6 και κάτω. Εγώ τρέχω 2.5.5, καθώς υπήρχε ήδη στο σύστημα και δεν την έχω ανανεώσει έκτοτε.

**Comment by p15zerv** [comment]
Από τη στιγμή που (μέχρι στιγμής τουλάχιστον) δεν προκαλεί προβλήματα η jekyll 4.0.0, δε βρίσκω λόγο να μη μεταβούμε σε αυτή. Από την άλλη, δεν προσφέρει απ' όσο είδα κάποιο ιδιαίτερα χρήσιμο πλεονέκτημα, πέρα από τη βελτιωμένη απόδοση.

Ως προς τη ruby, τρέχω σε διαφορετικά συστήματα και 2.5 και 2.6 χωρίς κάποιο πρόβλημα. Εφόσον η 2.7 βγάζει όντως warnings, είναι μάλλον κακή ιδέα να γίνει upgrade σε αυτή. 

Τελικά, ο κανόνας που αναφέρει ο @constantinexisc είναι μάλλον κι ο σωστός. Αν θέλουμε να προσδιορίσουμε το εύρος λίγο παραπάνω ας πούμε από 2.4 μέχρι και 2.6, μιας και 2.4+ προτείνει η jekyll 4.0.0.

**Comment by NikosAvg** [comment]
Κατά τη γνώμη μου η μετάβαση σε μεταγενέστερη έκδοση πρέπει να γίνει όταν αυτή έχει δοκιμαστεί αρκετά για να είμαστε σίγουροι οτι δεν θα υπάρξουν προβλήματα και από τι στιγμή που δεν είναι υποχρεωτική η αναβάθμιση προτείνω να μην γίνει ακόμα.

**Comment by dimpram** [comment]
Εντέλει έχει αναλάβει κάποιος αυτό το issue όσο αφορά το .ruby-version? Έχουμε καταλήξει κάπου?

**Comment by epidrome** [comment]
αυτό το θέμα είναι περισσότερο για την σχετική συζήτηση παρά για να το κλείσουμε με κάποιο αίτημα, άλλωστε αν είδες δεν έχει `PR welcome`

**Comment by provopoulos** [comment]
Nice dependency hell.

_Νομίζω_ πως σε τέτοια ζητήματα είναι καλή πρακτική να δημιουργούνται branches με τις τελευταίες εκδόσεις (π.χ. Ruby v3.0) για να γνωρίζομε τις πιθανές ασυμβατότητες (όπως σπασμένα plugins, κτλ.) εκ προοιμίου ώστε να υπάρξει και σχετικός προγραμματισμός/συζήτηση για την αναβάθμιση.
Σίγουρα δεν είναι ένα ζήτημα που μας επηρεάζει άμεσα αλλά δεν πρέπει να γίνει ζήτημα τελευταίας στιγμής διότι μπορεί να εξελιχθεί σε πολύ επίπονη διαδικασία.
Αυτή τη στιγμή δε μπορούμε να κάνουμε κάποια σχετική ενέργεια διότι η Ruby v3.0 δεν έχει κυκλοφορήσει, ωστόσο όταν έρθει αυτή η στιγμή καλό θα ήταν να προχωρήσουμε στην προαναφερθείσα διαδικασία και να παρακολουθούμε τα ανοιχτά ζητήματα στο ίδιο το θέμα: https://github.com/mmistakes/minimal-mistakes/issues

**Comment by dimpram** [comment]
News! https://github.com/jekyll/jekyll/releases/tag/v4.0.1

> "Prevent console warnings with Ruby 2.7"

**Comment by KonstantinosG** [comment]
Τις προηγούμενες ημέρες δεδομένου ότι μου ζητούσε το bundle αναβάθμιση θεώρησα πως θα ήταν καλό να γίνει αναβάθμιση σε Ruby 2.7 την οποία και έκανα. Το κομμάτι με το οποίο είχα ασχοληθεί σχετίζεται με την εισαγωγή της σελίδας "Επικοινωνία" (#69) εντός της οποίας έχουν εισαχθεί επίσης και χάρτες με Leaflet. Οι χάρτες λοιπόν δεν μπορούσαν να προβληθούν πλέον μετά την αναβάθμιση. Θα πρότεινα έως ότου υπάρξει καλύτερη υποστήριξη της Ruby 2.7 να αποφεύγαμε την αναβάθμιση σε αυτήν. Περισσότερες πληροφορίες για το πρόβλημα στο issue #136.

**Comment by epidrome** [comment]
@KonstantinosG μήπως υπάρχει κάποια επισημη τεκμηρίωση-λινκ για αυτό το πρόβλημα; μου κάνει εντύπωση που οι χάρτες έχουν πρόβλημα γιατί είναι θέμα κλιεντ ενώ η ρουμπι είναι στον σερβερ.

**Comment by KonstantinosG** [comment]
@epidrome δεν έχω βρει κάποια σχετική ανάρτηση που αναφέρει και να στηρίζει το πρόβλημα αυτό. Στο [repo](https://github.com/DavidJVitale/jekyll-leaflet) του leaflet για jekyll δεν αναφέρει προτεινόμενη έκδοση για τους χάρτες. Η μόνη αναφορά σε έκδοση είναι σε [αυτό](https://github.com/DavidJVitale/jekyll-leaflet/blob/acf44b4295b935306f05fa82aed796c61b5de040/jekyll-leaflet.gemspec) το αρχείο όπου αν δεν κάνω λάθος είναι εκδοση του leaflet.

**Comment by epidrome** [comment]
αν θεωρείς πως έχεις βρει ένα νέο μπαγκ καλό είναι να το περιγράψεις στο αποθετήριο του λιφλετ
