### ISSUE TITLE
Προσθήκη Βίντεο στο Υπόβαθρο ή/και κατά πλάτος στην Αρχική Σελίδα

### ISSUE THREAD

**Issue by Spirosvw** [ioniodi/site-gr#95]
### Δήλωση Θέματος
- Προσθήκη Πολυμέσων-Βίντεο στην Αρχική Σελίδα
- Προσθήκη βίντεο στην αρχική σελίδα το οποίο θα παίζει στο background της σελίδας.
- Δυσκολία Θέματος: Δύσκολο

### Απορίες σχετικά με το θέμα (αν υπάρχουν)
-Υπάρχει κάποια προτίμηση για το υλικό του βίντεο (Για την υλοποίηση σκεφτόμουν να χρησιμοποιήσω την 3d περιήγηση του τμήματος μας)?

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request έχω πάρει το "πράσινο φως"

**Comment by epidrome** [comment]
για αρχή ένα βίντεο ή/και γκιφ που βασίζεται στο 3Δ νομίζω πως είναι αρκετό για δοκιμές

καλό είναι να μας στείλεις μερικές σχετικές σελίδες και τεχνολογίες για συζήτηση παρακάτω

**Comment by epidrome** [comment]
σας έχει γίνει ανάθεση αλλά δεν έχετε στείλει κάποιο σχόλιο!

@KonstantinosG 
@andreanastil
@NikosAvg

**Comment by Spirosvw** [comment]
Δεν έχω κάνει ακόμα κάποια προσθήκη λόγω ανειλημμένων υποχρεωσεων. Αν θέλετε απλά να μου πείτε την άποψη σας για την ιδέα αυτή και αν έχετε να προτείνετε κάτι καλύτερο.

**Comment by NikosAvg** [comment]
Εγώ θα πρότεινα τουλάχιστον για αρχή να μην προσθέσουν βίντεο αλλά εικόνες τύπου gif πρώτον για να δούμε πως θα δουλεύουν και δεύτερον για να μην βαρύνουμε το αποθετήριο με πολύ μεγάλα αρχεία όπως ένα βίντεο.

**Comment by KonstantinosG** [comment]
Θεωρώ καλή την ιδέα του βίντεο αλλά για να αποφύγουμε το να βαρύνει το αποθετήριο θα μπορούσε να χρησιμοποιηθεί το youtube embed (αν δεν κάνω λάθος υπάρχει στο youtube η τριδιαστατη περιήγηση, ένα παράδειγμα είναι αυτό: https://www.youtube.com/watch?v=gz_akFO-SlM)

**Comment by epidrome** [comment]
> καλό είναι να μας στείλεις μερικές σχετικές σελίδες και τεχνολογίες για συζήτηση παρακάτω

**Comment by Spirosvw** [comment]
Πιθανή προσέγγυση:
1) https://github.com/mmistakes/minimal-mistakes/issues/101
2) https://stackoverflow.com/questions/10529859/how-to-include-video-in-jekyll-markdown-blog

**Comment by Spirosvw** [comment]
Στο δεύτερο λινκ η εισαγωγή του βίντεο γίνεται απλά με την προσθήκη ενός λινκ του youtube το οποίο είναι θετικό καθώς δεν επιβαρύνει το αποθετήριο αλλά υπάρχει το ρίσκο, σε περίπτωση που κατεβεί για κάποιο λόγο το βίντεο από το youtube, να χαθεί το βίντεο από την σελίδα.

**Comment by KonstantinosG** [comment]
> Στο δεύτερο λινκ η εισαγωγή του βίντεο γίνεται απλά με την προσθήκη ενός λινκ του youtube το οποίο είναι θετικό καθώς δεν επιβαρύνει το αποθετήριο αλλά υπάρχει το ρίσκο, σε περίπτωση που κατεβεί για κάποιο λόγο το βίντεο από το youtube, να χαθεί το βίντεο από την σελίδα.

πράγματι θα είναι πρόβλημα αυτό. Νομίζω πως μπορεί να παρακαμφθεί όμως με έναν έλεγχο για το αν το βίντεο είναι διαθέσιμο. Στην περίπτωση που δεν θα είναι να προβάλλεται μία εικόνα του τμήματος στη θέση του.

**Comment by epidrome** [comment]
υπάρχει κάποιο λινκ όπου να φαίνεται ότι το βίντεο είναι πλήρους-πλάτους;

**Comment by Spirosvw** [comment]
Δεν διαθέτω ακόμα κάποιο ετοιμο Demo για να σας δείξω αν εννοείτε αυτό. Ακόμα  δυσκολεύομαι λίγο με την κατανόηση του συνδυασμού markdown-  liquid στα αρχεία και στο πως να υλοποιώ αλλαγές στο Remote-Theme για να υλοποιήσω το issue αυτό

**Comment by epidrome** [comment]
νομίζω ότι ένα απλό ντέμο μπορει να γίνει απευθείας στον chrome με αλλαγές στο debug-developer mode, αφού αυτή η εργασία είναι κυρίως τεχνολογία front-end

τα λινκ που έστειλες παραπάνω δεν φαίνεται να έχουν βίντεο πλήρους-πλάτους
https://github.com/ioniodi/site-gr/issues/95#issuecomment-621692144

**Comment by Spirosvw** [comment]
@epidrome έχω ολοκληρώσει σχεδόν την υλοποίηση. Θα ανεβάσω σύντομα ενα demo για να δειτε. Χρειάζονται κάποιες προσθήκες στο minimal ionio. Να ανοίξω και εκεί ένα issue ή να κάνω απευθείας pull request όταν είναι έτοιμο?

**Comment by Spirosvw** [comment]
Live demo: https://angry-joliot-8f953a.netlify.app/
Εντυπώσεις;

**Comment by NikosAvg** [comment]
Πολύ καλό Σπύρο και δεν καθυστερεί καθόλου.

**Comment by epidrome** [comment]
@Spirosvw μπράβο, φαίνεται ωραίο, 

μήπως να βάλεις εδώ και ένα λινκ προς τον κώδικα σου ώστε να τον σχολιάσουν οι συντελεστές @KonstantinosG @AsteriosP @andreanastil @NikosAvg πριν προχωρήσεις στο αίτημα;

τα δικά μου σχόλια, υπάρχει δυνατότητα για: 

1. περισσότερα από ένα βίντεο;
2. έλεγχο της σύνδεσης-συσκευής ώστε να μην παίζει σε μικρές-αργές συσκευές ή ώστε να έχουμε διαφορετική αρχική σελίδα για τους αργούς;

**Comment by Spirosvw** [comment]
> @Spirosvw μπράβο, φαίνεται ωραίο,
> 
> μήπως να βάλεις εδώ και ένα λινκ προς τον κώδικα σου ώστε να τον σχολιάσουν οι συντελεστές @KonstantinosG @AsteriosP @andreanastil @NikosAvg πριν προχωρήσεις στο αίτημα;
> 
> τα δικά μου σχόλια, υπάρχει δυνατότητα για:
> 
> 1. περισσότερα από ένα βίντεο;
> 2. έλεγχο της σύνδεσης-συσκευής ώστε να μην παίζει σε μικρές-αργές συσκευές ή ώστε να έχουμε διαφορετική αρχική σελίδα για τους αργούς;

Ως προς το δεύτερο ερώτημα θα πρέπει να το κοιτάξω    Αυτή την στιγμή ο κώδικας μου δίνει την δυνατότητα αλλαγής από βίντεο στο υπόβαθρο σε εικόνα στο υπόβαθρο με την αλλαγή μιας μόνο γραμμής άρα μπορεί να γίνει με κάποιον έλεγχο (δεν γνωρίζω προς το παρόν κάποιο τρόπο να ελέγξω αυτό που λετε).

Για το πρώτο ερώτημα σας εάν εννοείτε να παίζει πολλά βίντεο παράλληλα το ένα δίπλα στο άλλο, αυτό δεν είναι δυνατό με τον κώδικα μου καθώς στο Layout μπαίνει ένα βίντεο μόνο. Αν εννοούσατε όμως το βίντεο στο υπόβαθρο να μην είναι συνέχεια το ίδιο αλλά να παίζει ένα από μια συλλογή και κάθε φορά να αλλάζει δυναμικά, αυτό ίσως είναι εφικτό αφού το link του βίντεο αλλάζει εύκολα στο Index.html

**Comment by AsteriosP** [comment]
@Spirosvw πολύ καλή δουλεία μπράβο!!

έγω έχω μερικούς ενδοιασμούς για το βίντεο:

1. Το βιντεο νομίζω ότι είναι πολύ μεγάλο στον κάθετο άξονα διότι σου τραβάει την προσοχή πολύ περισσότερο σε σχέση με το κείμενο που υπάρχει πάνω από αυτό και την υπόλοιπη σελίδα. 

2. Σε περίπτωση που μείνει σε αυτή την μορφή το βίντεο θα πρότεινα να μπουν περισσότερες πληροφορίες για το τμήμα αλλά και πάλι αυτές να μην πιάνουν όλη την σελίδα σε πλάτος.

**Comment by Spirosvw** [comment]
https://github.com/Spirosvw/minimal-ionio/tree/add-video-background
Σε αυτό το branch έχουν γίνει αλλαγές/ προσθήκες:
_layouts/video-layout (περιέχει το νέο Layout που χρησιμοποιείται στο Index.html του Site)
_includes/video_background.html (περιέχει τον κώδικα html που έχει να κάνει με το περιεχόμενο)
_sass/minimal-mistakes/_page (προσθήκη νέου css style με όνομα .backgroudvid)


https://github.com/Spirosvw/site-gr/tree/add-video-background
Σε αυτό το branch έχουν γίνει αλλαγές: 
Στο index.html στο header προκειμένου η σελινα να εμφανίζει το αντίστοιχο περιεχόμενο

**Comment by GIANNIS-AGGELIS** [comment]
@Spirosvw  πολύ Καλή δουλιά έχεις κάνει θα συμφωνήσω και εγώ σε αυτά που είπε @AsteriosP  παραπάνω. Θα πρότεινα παμε κατεθειαν για gif αν υπάρχει αυτή η δυνατότητα και είναι εύκολο το οποίο επαναλαμβάνατε γιατί όταν τελειώσει το video δείχνει τα περιεχόμενα για το επόμενο video από το youtube.


![image](https://user-images.githubusercontent.com/22667836/81749022-8d5d9a00-94b3-11ea-9440-95a6aecb0dbd.png)

Επίσης το gif δεν θα τρώει τόσα πολλά δεδομένα από τον χρήστη όταν ειναί από κινητό

**Comment by epidrome** [comment]
> Ως προς το δεύτερο ερώτημα θα πρέπει να το κοιτάξω Αυτή την στιγμή ο κώδικας μου δίνει την δυνατότητα αλλαγής από βίντεο στο υπόβαθρο σε εικόνα στο υπόβαθρο με την αλλαγή μιας μόνο γραμμής άρα μπορεί να γίνει με κάποιον έλεγχο (δεν γνωρίζω προς το παρόν κάποιο τρόπο να ελέγξω αυτό που λετε).

νομίζω ότι υπάρχουν κάποιες βιβλιοθήκες javascript που δίνουν προφιλ των δυνατοτήτων του τερματικού του χρήστη. σκεφτείτε ότι 50% μπαίνουν με ταμπλετ-κινητά, στα κινητά ειδικά μάλλον δεν θέλουμε να στέλνουμε βίντεο ή μεγάλα αρχεία γκιφ.
https://demos.jquerymobile.com/1.4.0/rwd/

> Για το πρώτο ερώτημα σας εάν εννοείτε να παίζει πολλά βίντεο παράλληλα το ένα δίπλα στο άλλο, αυτό δεν είναι δυνατό με τον κώδικα μου καθώς στο Layout μπαίνει ένα βίντεο μόνο. Αν εννοούσατε όμως το βίντεο στο υπόβαθρο να μην είναι συνέχεια το ίδιο αλλά να παίζει ένα από μια συλλογή και κάθε φορά να αλλάζει δυναμικά, αυτό ίσως είναι εφικτό αφού το link του βίντεο αλλάζει εύκολα στο Index.html

να παιζεί πολλά βίντεο στην σειρά, το ένα μετά το άλλο.

**Comment by KonstantinosG** [comment]
Προσωπικά συμφωνώ με τον @AsteriosP σχετικά με το resize του βίντεο. Δεν κρίνω απαραίτητο να εισαχθεί gif. Ενδεχομένως να προσθέσει περισσότερο βάρος στην εκτέλεση της ιστοσελίδας καθώς θα πρέπει να εκτελείται και κώδικας javascript. Είχαμε συζητήσει στην αρχή του εξαμήνου σχετικά με την εισαγωγή πολλαπλών τεχνολογιών για την εξυπηρέτηση της ιστοσελίδας και θεωρήσαμε πως θα ήταν καλό να το αποφύγουμε.

**Comment by Spirosvw** [comment]
* Ως προς την χρήση του GIF δεν είμαι σίγουρος οτι συμφωνώ διότι θα επιβαρύνουν το repository.
* Με την μείωση του μεγέθους το βίντεο φαίνεται όπως στην εικόνα που έχω προσθέσει (μαύρο δεξια-αριστερά). 
![img](https://user-images.githubusercontent.com/22668228/81857610-2ac7d500-956b-11ea-8287-368a98964e5b.png)

* Για το κομμάτι της loop στο τέλος του βίντεο που εντόπισε ο @GIANNIS-AGGELIS , διόρθωσα το πρόβλημα.

* Για το κομμάτι το κομμάτι της πολλαπλής αναπαράστασης βίντεο, το ένα μετά το άλλο που ανέφερε ο @epidrome θα το κοιτάξω αλλά έαν οι αλλαγές που έχουν γίνει σας φαίνονται πολλές μπορώ να το κάνω σε ξεχωριστώ issue

* Για το κομμάτι του ελέγχου της συσκευής από την οποία μπαίνει ο χρήστης, απαιτείται η υλοποίηση κώδικα javascript. Ο πρώτος ενδοιασμός που έχω έχει να κάνει με αυτό που ανέφερε ο @KonstantinosG (εισαγωγή πολλαπλών τεχνολογιών). Επειδή αυτό καλεί επίσης για περισσότερες προσθήκες/αλλαγές θα μπορούσα να το κάνω σε ξεχωριστό issue

**Comment by Spirosvw** [comment]
Ως προς την πολλαπλή αναπαράσταση βίντεο, το Youtube API επιτρέπει την δημιουργία ενός playlist με τα βίντεο που θέλουμε να εμφανίζονται. Το youtube δίνει ένα μοναδικό id σε αυτό το playlist το οποίο λειτουργεί σαν το url ενός απλού βίντεο.

**Comment by epidrome** [comment]
> Με την μείωση του μεγέθους το βίντεο φαίνεται όπως στην εικόνα που έχω προσθέσει (μαύρο δεξια-αριστερά).

νομίζω πως είναι πιο συνεπές (με το θέμα, αλλά και με την πρακτική άλλων σελίδων) το βίντεο να είναι πλήρους πλάτους, το γεγονός ότι έχει πολύ ύψος μπορεί να διορθωθεί με κροπάρισμα του βίντεο ή/και δημιουργία νέων βίντεο με δεδομένες προδιαγραφές.

συμφωνώ ότι η λίστα βίντεο καθώς και ο έλεγχος συσκευής του χρήστη θα μπορούσαν να είναι νέα θέματα
