### ISSUE TITLE
Μετατροπή δομής για τη βιβλιογραφία των μαθημάτων σε bibtex

### ISSUE THREAD

**Issue by p15zerv** [ioniodi/site-gr#96]
### Δήλωση Θέματος
- Τίτλος: Μετατροπή δομής για τη βιβλιογραφία των μαθημάτων σε bibtex
- Στόχοι:
  1. Μετατροπή της υπάρχουσας δομής για τη βιβλιογραφία μαθημάτων (#80) σε bibtex. Αυτό θα γίνει με τη βοήθεια του gem `jekyll-scholar`, ώστε να ακολουθούμε ένα πιο καλά τεκμηριωμένο και αξιόπιστο format για την αναπαράσταση της βιβλιογραφίας.
  2. Ανάκτηση των πληροφοριών όλων των υφιστάμενων βιβλίων μέσω του site του Εύδοξου και αποθήκευσή τους σε δομή bibtex. Αυτό έχει (σχεδόν) ολοκληρωθεί τοπικά, αλλά με αυτοποιημένο τρόπο, οπότε ενδέχεται κάποια στοιχεία να μην είναι σωστά ή να μη συμβαδίζουν απόλυτα με το συντακτικό του bibtex (καθώς στον Εύδοξο δεν ακολουθούν κάποιο σταθερό format).
  3. Ανάκτηση και αποθήκευση περαιτέρω πληροφοριών από τον Εύδοξο (όπως φωτογραφία από εξώφυλλο, σύντομη περιγραφή, κλπ) για τη δυναμική εμφάνιση περιεχομένου #74. 
- Δυσκολία Θέματος: Δεν συμπεριλαμβάνεται στο roadmap. Σε συνδυασμό με το #74, μάλλον Δύσκολο.

### Σχόλια

- Ρίχνοντας μια ματιά στο σχόλιο από @epidrome στο #80, ο Κάλλιπος δε φαίνεται να έχει πολλά από τα βιβλία που χρησιμοποιούνται ήδη στο site (αν κατάλαβα καλά περιέχει μόνο δωρεάν συγγράμματα). Επομένως, δε νομίζω να βολεύει για την ανάκτηση περιεχομένου για τώρα.
- Τίθενται μερικά ζητήματα ως προς τη συσχέτιση μεταξύ ενός course και ενός (ή πολλών) bibtex citation(s), τα οποία μάλλον θα πρέπει να συζητηθούν σε κάποια διάλεξη. Σε ό,τι έχει να κάνει με την εμφάνιση των αναφορών, θα είναι μάλλον συνετό να προστεθούν τα σχετικά αρχεία στο minimal-ionio.

### Υπενθυμίσεις
- [x] Έχω ελέγξει ότι το περιέχομενο των αλλαγών μου δεν το έχει δηλώσει κάποιος άλλος
- [x] Πριν προχωρήσω σε pull request έχω πάρει το "πράσινο φως"

**Comment by epidrome** [comment]
από παλιά έχουμε το σχετικό αποθετήριο με έμφαση στις δημοσιεύσεις που έχει μείνει στην μέση
https://github.com/ioniodi/scholardi
μήπως σε ενδιαφέρει να παίξεις εκεί ελεύθερα?

ο προβληματισμός-σκεπτικό μου είναι παρόμοιος-ανάλογος με τα σχόλια μου #75  
μήπως φορτώνουμε πολύ εδώ με νέες δομές-τζεμ και αυξάνουμε την δυσκολία
για τους μελλοντικούς συνεργάτες περιεχομένου-κώδικα που θα έχουν μια
ακόμη τεχνολογία να μάθουν

θα ήθελα και την γνώμη κυρίως του @GIANNIS-AGGELIS και των άλλων που πρόσθεσα, 
γιατί εγώ δεν είμαι αντικειμενικός αφού δουλεύω με το bibitex, jekyll-scholar 5+χρόνια

**Comment by p15zerv** [comment]
> από παλιά έχουμε το σχετικό αποθετήριο με έμφαση στις δημοσιεύσεις που έχει μείνει στην μέση
https://github.com/ioniodi/scholardi
μήπως σε ενδιαφέρει να παίξεις εκεί ελεύθερα?

Για τώρα δουλεύω κυρίως στο κομμάτι της ανάκτησης και αποθήκευσης της πληροφορίας που δίνει ο Εύδοξος, οπότε γίνεται τοπικά. Με μία γρήγορη δοκιμή στο δικό μας site το jekyll-scholar είδα να λειτουργεί χωρίς προβλήματα, αλλά αν χρειαστεί να πειραματιστώ με κάτι θα το έχω υπόψιν.

> ο προβληματισμός-σκεπτικό μου είναι παρόμοιος-ανάλογος με τα σχόλια μου #75
μήπως φορτώνουμε πολύ εδώ με νέες δομές-τζεμ και αυξάνουμε την δυσκολία
για τους μελλοντικούς συνεργάτες περιεχομένου-κώδικα που θα έχουν μια
ακόμη τεχνολογία να μάθουν

Σύμφωνος με αυτό, όμως:
- Από τη μία, η χρήση bibtex δεν είναι αναγκαία. Μπορούμε να μείνουμε στην υπάρχουσα δομή και οι στόχοι ii. και iii. που αναφέρω παραπάνω εξακολουθούν να είναι έγκυροι, με τελικό στόχο την υλοποίηση του #74 
- Από την άλλη, το bibtex με το αντίστοιχο gem παρέχει ακριβώς τις λειτουργίες που θέλουμε: ένα συνοπτικό κείμενο, όταν κάνουμε cite ένα βιβλίο στη σελίδα κάθε μαθήματος, κι ένα αναλυτικό, σε σελίδα αποκλειστικά για το βιβλίο (αντίστοιχη δομή με τα courses). Αν πούμε ότι δε χρησιμοποιούμε άλλες τεχνολογίες, τα αρχεία για την εμφάνιση θα έπρεπε να μπουν στο theme, όπου αποκρύπτονται μέσω include και προκύπτουν αργότερα στην πορεία ενός νέου χρήστη. Μέσω του jekyll-scholar, αυτά παρέχονται αυτόματα, με περισσότερες δυνατότητες από αυτές που θα δίναμε εμείς, όμως έπειτα από ένα αρχικό learning curve.

> θα ήθελα και την γνώμη κυρίως του @GIANNIS-AGGELIS και των άλλων που πρόσθεσα,
γιατί εγώ δεν είμαι αντικειμενικός αφού δουλεύω με το bibitex, jekyll-scholar 5+χρόνια

Αν το δούμε πιο σφαιρικά, όλη η συζήτηση γίνεται κυρίως για την τοπική αποθήκευση πληροφορίας των βιβλίων, ώστε να εμφανίζεται μέσω του #74. Πιθανό να μην αξίζει όλος ο κόπος και οι νέες τεχνολογίες, οπότε  να επιμείνω στον στόχο ii. μιας και είναι σχεδόν έτοιμος, ώστε να μεταβούμε στη νέα δομή χωρίς να μείνει κάτι για πολύ εύκολα-εύκολα, και να κλείσει εκεί.

Ας δούμε και την άποψη των υπολοίπων για να δούμε πως συνεχίζουμε...

**Comment by p15zerv** [comment]
Έχω αφήσει τις αλλαγές που έχω μέχρι στιγμής στο αποθετήριο: https://github.com/p15zerv/site-gr/tree/gh-pages ώστε να έχουν μια ιδέα κι οι υπόλοιποι για το συντακτικό και τα αρχεία που περιλαμβάνουν οι προτεινόμενες αλλαγές.

Αφήνω κι ενδεικτικά ένα μάθημα με τις δύο εναλλακτικές για τα citations: 
https://adoring-yonath-300689.netlify.com/courses/ai/. Μην εστιάσετε στο θέμα της εμφάνισης, αλλάζει από το config αν προχωρήσουμε με το jekyll-scholar. Περισσότερο ενδιαφέρον έχει πλέον η δομή των σχετικών αρχείων: 
- φάκελος `_bibliography/` για το bib
- χρήση {% cite %} και {% bibliography %} εντολών σε κάθε μάθημα

**Comment by ghost** [comment]
Προσωπικα μου αρεσουν και οι δυο προσεγγισεις του @GIANNIS-AGGELIS  και του @p15zerv , πιστευω πρεπει να μετρησουν και οι δυο προσπαθειες σαν κατι "ολοκληρωμενο" ακομη και αν πρεπει να διαλεξουμε μονο μια. 

Η τελικη αποφαση πιστευω ειναι εντελως βασισμενη σε trade-offs και θα πρεπει να την παρει ο @epidrome , η προσεγγιση του @GIANNIS-AGGELIS ειναι πιο ευθυγραμμισμενη με την φιλοσοφια του jekyll, αλλα η προσπαθεια του @p15zerv ειναι πιο επεκτασιμη και πιστευω δεν χρειαζεται πολυ μεγαλο χρονο εξοικειωσης για καποιο νεο contributor σε σχεση με την πρωτη μεθοδο.

Μπραβο και στους δυο παντως για την δουλεια.

**Comment by epidrome** [comment]
@AsteriosP @korinaal @GIANNIS-AGGELIS 
your comments?

**Comment by korinaal** [comment]
@epidrome θεωρώ ότι η προσέγγιση με το bibtex είναι πιο συμφέρουσα τόσο για το site, καθώς είναι επεκτάσιμη, όσο και για τους νέους φοιτητές. Αναφορικά με τους φοιτητές, εκ των πραγμάτων θα χρειαστεί να αφιερώσουν χρόνο για να εξοικειωθούν με το site και τη λειτουργία του. Σε περίπτωση χρήσης του bibtex (το οποίο έχει μια κατανοητή δομή-συντακτικό) δίνεται και η ευκαιρία να μάθουν ένα εργαλείο που θα τους φανεί χρήσιμο και εκτός του site.

**Comment by GIANNIS-AGGELIS** [comment]
@epidrome 
Θα συμφωνήσω με τα λεγόμενα του @constantinexisc  μπορεί η δικιά μου υλοποίηση να είναι πιο κοντά στη φιλοσοφία του jekyll άλλα πιστεύω ότι το bibtex έχει περισσότερες δυνατότητες. Όσον άφορα την την εκμάθηση θα συμφωνήσω και με την @korinaal στο ότι θα σου χρειαστεί και έκτος του site. Από την προσωπική μου εμπειρία δεν θεωρώ ότι είναι κάτι τρομερά δύσκολο.
Μπράβω στον @p15zerv

**Comment by epidrome** [comment]
@AsteriosP comments?

**Comment by epidrome** [comment]
ένα νέο θέμα #97 δημιουργεί πρόσθετες σκέψεις

θέλουμε εξωτερικούς χρήστες να μπορούν να επεξεργαστούν αρχεία (π.χ., ανακοινώσεις, αλλαγή βιβλίου) χωρίς να μπαίνουν στο γκιτχαμπ

σε αυτό το πλαίσιο αναρωτιέμαι:

πόσο στιβαρή είναι η λύση εδώ σε περίπτωση που γίνει λάθος στην αυστηρή δομή δεδομένων του μπιμπτεχ σε σχέση με το σκέτο μαρκ-νταουν

**Comment by AsteriosP** [comment]
εγώ είμαι γενικά υπέρ στο να χρησιμοποιώ όποια τεχνολογία είναι κατάλληλη στο κάθε task που έχω να κάνω, όποτε είμαι και υπέρ του bibtex διότι είναι μία τεχνολογία που είναι ξεκάθαρα για βιβλιογραφία και όχι για κάτι άλλο. 

πάνω σε αυτό έχω να προσθέσω ότι αν τελικοί χρήστες είναι είναι φοιτητές πληροφορικής τότε αποτελεί μία κάλλη επιλογή για την εκμάθηση άλλων τεχνολογιών από αυτών του jekyl και της liquid.

Σε διαφορετική περίπτωση όπου θεωρούμε ότι ο χρήστης είναι άσχετος από πληροφορική τότε θεωρώ πώς είναι πιο συμβατή η λύση της δόμης αλλά φυσικά όχι η τέλεια. Σε αυτή την περίπτωση θεωρώ πως είναι συνετή η δημιουργία κάποιας GUI εφαρμογής εάν είναι δυνατόν.

**Comment by epidrome** [comment]
παραθέτω μερικά σχόλια από @constantinexisc και @p15zerv τα οποία συνοψίζουν την κατάσταση:

> Η τελικη αποφαση πιστευω ειναι εντελως βασισμενη σε trade-offs και θα πρεπει να την παρει ο @epidrome , η προσεγγιση του @GIANNIS-AGGELIS ειναι πιο ευθυγραμμισμενη με την φιλοσοφια του jekyll, αλλα η προσπαθεια του @p15zerv ειναι πιο επεκτασιμη και πιστευω δεν χρειαζεται πολυ μεγαλο χρονο εξοικειωσης για καποιο νεο contributor σε σχεση με την πρωτη μεθοδο.

> Αν το δούμε πιο σφαιρικά, όλη η συζήτηση γίνεται κυρίως για την τοπική αποθήκευση πληροφορίας των βιβλίων, ώστε να εμφανίζεται μέσω του #74

η τρέχουσα κατανόηση που έχω για το θέμα είναι πως ιδανικά δεν θέλουμε να αποθηκευουμε τοπικά τίποτα εκτός από ένα λινκ-αναγνωριστικό προς τον εύδοξο, όμως αυτό δεν είναι εφικτό για την ώρα γιατί όπως μας είπε ο @p15zerv ο εύδοξος δεν έχει ΑΡΙ

επομένως, αφού είμαστε αναγκασμένοι να αποθηκεύουμε τοπικά διπλή πληροφορία (=κακή πρακτική) ας το κάνουμε με καλή πρακτική (=στάνταρ φορμά αρχείου). 

παραμένω επιφυλακτικός για την "ευχρηστία" γιατί το μπιτεχ δεν συγχωρεί λάθη, αλλά ας το δοκιμάσουμε!

ευχαριστώ την ομάδα του θέματος για την ενδιαφέρουσα συζήτηση και κυρίως τον @p15zerv για την πρωτοβουλία 🚀

**Comment by epidrome** [comment]
στην τεκμηρίωση θα ήθελα να δω αν/πως γίνεται στο μέλλον να φύγουμε από τζέκιλ(-σκολαρ)

ένας από τους λόγους που διάλεξα το τζεκιλ-σκολαρ για την προσωπική σελίδα μου, ήταν γιατί δεν μπορούσα να βρω κάτι άλλο να μου αρέσει στο πλαίσιο στατικ-μπιμπ-τεχ
https://scholar.epidro.me

οπότε καλό θα ήταν να έχουμε ένα πλάνο για (πιθανή) έξοδο, ώστε να μην είμαστε κλειδωμένοι στο τζεκιλ, άλλωστε αυτό είναι και (ανοιχτό) ζητούμενο στα (πολύ) δύσκολα

τα γράφω γιατί αν θυμάμαι σωστά ο @p15zerv είχε πει κάτι για  κάποια τοπικά σκριπτ για τις μετατροπές;

**Comment by p15zerv** [comment]
Νομίζω πως ναι, η μετατροπή θα ήταν σχετικά εύκολη. Όπως το έχω υλοποιήσει μέχρι στιγμής, όσα δεδομένα τράβηξα από τον Εύδοξο τα κράτησα σε ένα json με όλα τα σχετικά πεδία. Επομένως, μπορεί μετέπειτα να μετατραπεί με κάποιο script σε όποιο format χρησιμοποιούμε ή ακόμα και σε database με λίγη τροποποίηση ακόμα.

Οι κύριες αλλαγές θα είχαν να κάνουν με τον τρόπο εμφάνισης των δεδομένων μετά στη σελίδα, αλλά αυτό είναι έτσι κι αλλιώς ζήτημα αν φύγουμε τελείως από jekyll. Το jekyll-scholar στην προκειμένη περίπτωση απλώς κάνει τη ζωή μας πιο εύκολη για τώρα.

Βέβαια για όλα αυτά θα είμαι περισσότερο βέβαιος μόλις προχωρήσω πλέον με την υλοποίηση για να δω αν θα προκύψουν άλλα θέματα.
